### PR TITLE
Adding System Level tests for every Speciality IO cluster

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This pull request contains the System Level tests which validates the functionality of the new Cluster Read/Write methods in the NI VeriStand context.

### Why should this Pull Request be merged?

Currently there are no System Level tests which are validating the functionality of the new implementation of the Cluster Read/Write methods. These tests also confirm that the data types supported until now are still fully functional with the new implementation.

### What testing has been done?

Run the tests locally and they all passed.

### CODE REVIEW

**Comment by DStavilaNI** [comment]
I mostly agree with the changes. I would only suggest one modification:

image

The name is misleading - it should be more obvious that it is a LV Project containing the sources for the FPGA Bitfiles. Something like - > "Speciality IO LVFPGA Proj". Then the paths in the tests should be updated....

**Comment by DStavilaNI** [comment]
image

This is a rather shaky implementation. The assumption is that the channels will be updated in 100ms, which may not be the case on a lot of other systems, and depends on a lot of stuff, considering that it goes through multiple layers before it reaches the FPGA. Consider using instead the "While" loop approach with a timeout. We read as fast as we can until we get the expected values or a set timeout expires.

**Review by bogdanp-ni — APPROVED** [review]
I approve, as long as the feedback you already received is implemented. I am in favor of _not_ using a Stall Dataflow construct and going with a While loop instead.

**Comment by zszilagy** [comment]
> I mostly agree with the changes. I would only suggest one modification:
> 
> image
> 
> The name is misleading - it should be more obvious that it is a LV Project containing the sources for the FPGA Bitfiles. Something like - > "Speciality IO LVFPGA Proj". Then the paths in the tests should be updated....

Fixed as suggested.

**Comment by zszilagy** [comment]
> image
> 
> This is a rather shaky implementation. The assumption is that the channels will be updated in 100ms, which may not be the case on a lot of other systems, and depends on a lot of stuff, considering that it goes through multiple layers before it reaches the FPGA. Consider using instead the "While" loop approach with a timeout. We read as fast as we can until we get the expected values or a set timeout expires.

Replaced with while loop which iterates for 1 second OR until an error is thrown OR until the the expected values are read (whichever comes first).

**Pull request merged**
