### PR TITLE
Added Bitfile Parsing unit tests and Max Nr of Scalar channels system test

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Added Load and Parse unit tests and Max Nr of Scalar channels system test

### Why should this Pull Request be merged?

Parsing the FPGA bitfile had not unit test coverage.
Custom Device limitations needed testing.

### What testing has been done?

Run the tests locally using VI Tester and all tests passed.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
I realized that automatic bitfile naming will not be very helpful in understanding which bitfile is used on what target. Please rename all your bitfiles to contain the target's name.

**Comment by bogdanp-ni** [comment]
What was the value you found for the maximum number of scalars? What's the error you get for values larger than that? What is the limiting factor (who's generating that error) for that value?

**Comment by bogdanp-ni** [comment]
Rename:
test_Max Nr Of Scalar Channels Deployment.vi -> test_Max Nr Of Scalar Channels_Basic Deployment.vi

**Comment by bogdanp-ni** [comment]
Place your test VIs into a folder called "tests" at the same level with the test lvclass and replicate the same structure in the project using a virtual folder. Take a look at Scalar Channels Testing, for a good example.

**Comment by bogdanp-ni** [comment]
Remove testExample.vit and temp_VI_UnderTest.vi (something you already noticed).

**Comment by bogdanp-ni** [comment]
I would be curious to see if the FPGA Addon ignores Peer To Peer FIFOs, as it should. Please add one P2P Reader and one P2P Writer to your parsing test. I'm expecting them to NOT appear in the list of DMAs.

**Comment by DStavilaNI** [comment]
I agree with the comments above.  Additionally:
1.  I think the Assets folder should not be in the same Test Class folder, but rather next to it, since it is not actually part of the class. So, Ideally, we would need to have the following folder structure:

-Unit Tests (For Example)
     - My Test (test folder)
            - Assets (assets folder for the test class)
            - My Test (test class folder)

2. I would recommend adding the maximum number of scalar channels, for the FPGA Addon CD, to be added as part of the documentation of the CD ... either quick start and/or readme on git.

**Comment by csteavu** [comment]
> What was the value you found for the maximum number of scalars? What's the error you get for values larger than that? What is the limiting factor (who's generating that error) for that value?

The maximum number of scalar channels is 127 (inputs AND outputs);
The error for larger values states that: "The number of open RIO sessions exceeds the recommended limit. For optimal performance, close RIO sessions when you no longer need them."
A user can have more than 127 in the FPGA (outside of the Veristand context ), however the performance suffers as a result. Hence, Veristand will not allow a user to deploy a system definition with a greater number of scalars than recommended.

This explanation will be added as part of the documentation of the Custom Device

**Comment by csteavu** [comment]
> 1. I would recommend adding the maximum number of scalar channels, for the FPGA Addon CD, to be added as part of the documentation of the CD ... either quick start and/or readme on git.

The information regarding the number of scalar channels will be added as part of the documentation of the Custom Device and I suggest to track it under [User Story 1026282: Testing limitations of the FPGA Addon Custom Device](https://ni.visualstudio.com/DevCentral/_workitems/edit/1026282)

**Comment by DStavilaNI** [comment]
Hello Calin,

              The following errors, with missing files, came up when cloning and opening your new PR:
image

             I think it might be due to your recent refactoring efforts.

Sincerely yours,
Denis

**Comment by bogdanp-ni** [comment]
> > What was the value you found for the maximum number of scalars? What's the error you get for values larger than that? What is the limiting factor (who's generating that error) for that value?
> 
> The maximum number of scalar channels is 127 (inputs AND outputs);
> The error for larger values states that: "The number of open RIO sessions exceeds the recommended limit. For optimal performance, close RIO sessions when you no longer need them."
> A user can have more than 127 in the FPGA (outside of the Veristand context ), however the performance suffers as a result. Hence, Veristand will not allow a user to deploy a system definition with a greater number of scalars than recommended.
> 
> This explanation will be added as part of the documentation of the Custom Device

Personally, I really don't like that error message and I would have no idea how to get rid of it. Please add a task saying that we need to validate the error message with Marcelo and change it, if he agrees.

**Comment by DStavilaNI** [comment]
Feedback implemented :) ... the tests are running, so it should be good now

**Pull request merged**
