### PR TITLE
PPL Migration

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- This PR implements the migration towards a PPL (packed project libraries) based build for the FPGA Addon custom device.

### Why should this Pull Request be merged?

- Updates the project build specs from source distributions to packed project libraries.
- Updates Engine code to ensure PPL compatibility.
- Updates the custom device XML configuration file.
- Removes obsolete targets support.
- Updates system tests.
- Updates unit tests.

### What testing has been done?

Both the unit and the system tests are passing.

### CODE REVIEW

**Review by phutanu — CHANGES_REQUESTED** [review]
@DStavilaNI when diffs will be generated, I can start reviewing. Until then, I can't really do much.

**Comment by phutanu** [comment]
Referencing #139.

**Comment by Karl-G1** [comment]
I saw this PR had not built yet, so I [kicked one manually](https://nijenkins/view/Veristand/view/GitHub/job/NI/job/niveristand-fpga-addon-custom-device/view/change-requests/job/PR-144/). It looks like the first one failed to clone the repo randomly.

**Comment by phutanu** [comment]
> I saw this PR had not built yet, so I [kicked one manually](https://nijenkins/view/Veristand/view/GitHub/job/NI/job/niveristand-fpga-addon-custom-device/view/change-requests/job/PR-144/). It looks like the first one failed to clone the repo randomly.

Hey @Karl-G1, I noticed the manual build passed, but no diffs were generated. Do you have any idea why we have no diffs? Thanks!

**Comment by Karl-G1** [comment]
@phutanu @DStavilaNI 
The diff pipeline is timing out after an hour. 160 files may be too large for one PR if you want a visual diff, or you can work with @buckd to increase the timeout in certain cases.
image

**Review by phutanu — COMMENTED** [review]
@DStavilaNI: All the Error Strings need to be checked and confirmed by @WillCawley. This can be done also after we merge this PR.

**Comment by phutanu** [comment]
Is there a reason for doing this?
image

When you can already do this in LabVIEW:
image

**Comment by phutanu** [comment]
How do we validate that the dependency was added successfully if the code does not report any error when the refnum is invalid?
image

**Comment by phutanu** [comment]
Shouldn't we close also this references after deleting the child nodes?
image

**Comment by phutanu** [comment]
Are we validating this path somewhere?
image

**Comment by phutanu** [comment]
Why do we include dependencies for all the targets in the XML, when only `Windows` and `Linux_64` targets are supported for the next VeriStand release?
image

**Comment by phutanu** [comment]
Should we report an error in case the "Generated files in" array is empty?

image

**Comment by phutanu** [comment]
This can be included as a global variable and in case the Build Spec name for the configuration changes, it is an easy fix to change this globally.

image

**Comment by phutanu** [comment]
Can you please explain me more on why we close all the node references when the "Supported Target Type" is empty?

image

**Comment by phutanu** [comment]
We should validate this path before executing the code.

Can you please explain more regarding the "filtering" for `Custom Device` versus `Custom Devices`?

image

**Comment by phutanu** [comment]
Why are we closing this tag in both cases? This is not the case for other code submitted, and I am wondering why we decided to do it for this particular node.

image

**Comment by phutanu** [comment]
Typo.

image

**Comment by phutanu** [comment]
Why are we closing this reference? I would expect to have parity. If we open the reference outside of this VI, to close it when we are sure we are done with it.

image

**Comment by phutanu** [comment]
Regarding all the existing System Level tests that were modified in this PR.

We should not add mutation code to those before deploying, instead we should update the test assets (system definition files, etc) to the latest FPGA Addon version.

If we want to test mutation code specifically, let's add a specific test/tests for this.

We should not make system level tests dependent on mutation code/VIs. This is not reproducible, and not a good practice.

**Comment by DStavilaNI** [comment]
> Is there a reason for doing this? image
> 
> When you can already do this in LabVIEW: image
> 
> Also, this error cluster has got into a fight. image

Implemented

**Comment by DStavilaNI** [comment]
> How do we validate that the dependency was added successfully if the code does not report any error when the refnum is invalid? image

Implemented

**Comment by DStavilaNI** [comment]
> Shouldn't we close also this references after deleting the child nodes? image

No, it is deleted automatically by the "Remove Child" method.

**Comment by DStavilaNI** [comment]
> Why do we include dependencies for all the targets in the XML, when only `Windows` and `Linux_64` targets are supported for the next VeriStand release? image

implemented

**Comment by DStavilaNI** [comment]
> Should we report an error in case the "Generated files in" array is empty?
> 
> image

Implemented

**Comment by DStavilaNI** [comment]
> This can be included as a global variable and in case the Build Spec name for the configuration changes, it is an easy fix to change this globally.
> 
> image

I disagree and I think it would be unnecessary to do this kind of refactor here. If required, it could be done as part of a separate PR. As a matter of coding preference - I do avoid using Global or Local variables, unless completely necessary.

**Comment by DStavilaNI** [comment]
> Can you please explain me more on why we close all the node references when the "Supported Target Type" is empty?
> 
> image

This code is redundant, so it was removed.

**Comment by DStavilaNI** [comment]
> We should validate this path before executing the code.
> 
> Can you please explain more regarding the "filtering" for `Custom Device` versus `Custom Devices`?
> 
> image

Define "Validate" please. At this point in the code, we do not care yet if the project file exists or not at that particular location - this will happen later, once we attempt to open the Configuration XML derived from that path - and if it does not exist, an error will be thrown. What we care about here, is we can find an expected name and location for a CD XML file. This is based on the naming convention for custom devices - at least those generated via the LV CD Wizzard.  The XML file has to be somewhere on the project directory, and typically, it will have a format like  "Custom Device <CD Name>" or "Timing and Sync <CD Name>" depending on the CD type. 

What the code does, is attempt to find the CD configuration XML based on the project name and location -> this implies that the custom device is following the VS CD Conventions.

**Comment by DStavilaNI** [comment]
> Why are we closing this tag in both cases? This is not the case for other code submitted, and I am wondering why we decided to do it for this particular node.
> 
> image

This reference is not further needed, hence it is closed. There is no particular reasoning behind it - it was a simple styling choice

**Comment by DStavilaNI** [comment]
> Typo.
> 
> image

Implemented

**Comment by DStavilaNI** [comment]
> Why are we closing this reference? I would expect to have parity. If we open the reference outside of this VI, to close it when we are sure we are done with it.
> 
> image

image

There is parity. The reference is opened (and closed) within the same context.

**Comment by DStavilaNI** [comment]
> Regarding all the existing System Level tests that were modified in this PR.
> 
> We should not add mutation code to those before deploying, instead we should update the test assets (system definition files, etc) to the latest FPGA Addon version.
> 
> If we want to test mutation code specifically, let's add a specific test/tests for this.
> 
> We should not make system level tests dependent on mutation code/VIs. This is not reproducible, and not a good practice.

If dedicated tests are necessary to test specifically mutation, this can be done as part of a separate PR. 
Regarding this specific implementation choice -> As it is, this implementation has the advantage that the "mutation" code can easily be disabled if need be (for instance for debugging or other purposes). Since the assets are unmodified, they can be used to test a wider range of functionalities, pertaining to older versions of the CD.   
That being said, I did suggest during our sync-ups, that I would like to update the test assets to reflect the changes to the custom device, however, if I recall correctly, the decision was taken to not do so.

**Comment by Karl-G1** [comment]
Abandoning this PR. We are currently not pursuing this modification to the custom device.

**Pull request closed without merging**
