### PR TITLE
Added handler for bitpacked scalar data type change

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds a handler for the specific case where the data type of a Scalar Channel data type is modified when it's bitpacked.
Also, the Custom Device FPGA Addon.xml was modified, as the Static Scalar Channel type did not have a right click menu. The "Bitpacking" functionality is not available for this type but the "Delete" functionality should be accessible for every channel in the System Explorer.

### Why should this Pull Request be merged?

Swapping bitfiles while having a bitpacked scalar channel in the tree can cause issues when the data type is switched to one that doesn't support bitpacking. (or can be split to less channels as expected)

### What testing has been done?

Built the CD and did manual testing. Now it behaves as expected. Autotests will follow in the upcoming PR which contains further tests for Bitfile Reload feature.

### CODE REVIEW

**Comment by zszilagy** [comment]
As the diffbot is offline I attached a few screenshots with the modified VIs:

Update Scalar Channel Properties_Front Panel
Update Scalar Channel Properties_Block Diagram_1
Update Scalar Channel Properties_Block Diagram_2
Update Scalar Channel Properties_Terminals
Get Invalid Scalar Data Channels

**Review by DStavilaNI — APPROVED** [review]
Looks good :)

**Comment by bogdanp-ni** [comment]
In the PR description, please add an explanation for XML file changes.

**Review by bogdanp-ni — APPROVED** [review]
Change looks good, see my previous comment.

**Comment by zszilagy** [comment]
> In the PR description, please add an explanation for XML file changes.

Added a description about why I had to modify the XML file.

**Pull request merged**
