### PR TITLE
Fixed the tests that are failing on the ATS

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The tests on the ATS have been failing because the following reason:
- bitfile path in the system definition was not updating dynamically on run - resulted in missing file error.
- FXP bitfile reload tests was looking for the wrong data type value

### Why should this Pull Request be merged?

Several important tests are affected by this and the issues described above makes the ATS tests to fail.

### What testing has been done?

Run the tests locally and they all passed.

### CODE REVIEW

**Comment by DStavilaNI** [comment]
Here is my initial feedback regarding this PR: 

- I think that the ordering of the terminals on the BD does not correspond with the order of controls on the FP:

image

- The ordering of controls on the FP does not correspond with the ordering of terminals in the connector paine:

image

**Comment by DStavilaNI** [comment]
[Recommendation] - The Sysdef changes seem to be only cosmetic, without any specific utility from the ATS point of view. I would recommend rolling back those, since it would contribute to a better ease of tracking.

**Comment by DStavilaNI** [comment]
- The value here is measured in (s), and if this is the case, then "200" seems a bit too much as a timeout value ...

image

**Review by bogdanp-ni — APPROVED** [review]

**Comment by DStavilaNI** [comment]
- Missing error wire:
image

**Comment by DStavilaNI** [comment]
- Excessive timeout value:
image

**Review by DStavilaNI — CHANGES_REQUESTED** [review]
Please see the above comments

**Comment by zszilagy** [comment]
> Here is my initial feedback regarding this PR:
> 
> * I think that the ordering of the terminals on the BD does not correspond with the order of controls on the FP:
> 
> image
> 
> * The ordering of controls on the FP does not correspond with the ordering of terminals in the connector paine:
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> * The value here is measured in (s), and if this is the case, then "200" seems a bit too much as a timeout value ...
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> [Recommendation] - The Sysdef changes seem to be only cosmetic, without any specific utility from the ATS point of view. I would recommend rolling back those, since it would contribute to a better ease of tracking.

Rolled back unnecessary changes.

**Comment by zszilagy** [comment]
> * Excessive timeout value:
>   image

Fixed as requested.

**Pull request merged**
