### PR TITLE
Added unit tests for the bitfile reload functionality. 

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

1. Added unit tests to validate the "Reload Bitfile.vi" functionality
2. Moved the "Compare Scalar Clusters.vi" and "Generate Assets Path.vi" vi's from "Source/Tests/Unit Tests/Scripting API Testing/Scripting API Unit Tests/private" folder to "Source/Tests/FPGA Addon Test Class/protected/" so on inheritance every other test class can benefit from their functionality. (as a side effect all the VIs which use these were marked as "dirty" and had to be saved)
3. Implemented a fix for the "test_Get FPGA Bitfile.vi" unit test

### Why should this Pull Request be merged?

1. There were no unit tests which validated the functionality.
2. Only the tests under "Source/Tests/Unit Tests/Scripting API Testing/Scripting API Unit Tests/tests" are able to use the VIs at the moment.
3. The test was failing on the CI and locally.

### What testing has been done?

Run all related tests locally and they all passed.

### CODE REVIEW

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
Please fix conflicting changes.

**Comment by zszilagy** [comment]
> Please fix conflicting changes.

The conflicts were resolved.

**Comment by DStavilaNI** [comment]
As discussed earlier during the call, I would add the following feedback:

1. Bitfile names are excessively long, as it seems to include description as all. I would suggest using shorter names for the bitfiles and add description, separately as labels.

image

2. For the example bitfiles, the names of the groups for the inputs and outputs are the same. This makes it hard to judge the content and differentiate between them. I would suggest using an "InputGroup.Scalar"/"OutputGroup.Scalar" approach.

image

3. The above point applies for the DMA used as well:

image

I would suggest using the names "TargetToHost"/"HostToTarget" naming convention, used in the DMA bitfile configuration to add clarity.

**Comment by zszilagy** [comment]
> As discussed earlier during the call, I would add the following feedback:
> 
> 1. Bitfile names are excessively long, as it seems to include description as all. I would suggest using shorter names for the bitfiles and add description, separately as labels.
> 
> image
> 
> 1. For the example bitfiles, the names of the groups for the inputs and outputs are the same. This makes it hard to judge the content and differentiate between them. I would suggest using an "InputGroup.Scalar"/"OutputGroup.Scalar" approach.
> 
> image
> 
> 1. The above point applies for the DMA used as well:
> 
> image
> 
> I would suggest using the names "TargetToHost"/"HostToTarget" naming convention, used in the DMA bitfile configuration to add clarity.

Implemented as suggested.

**Review by bogdanp-ni — APPROVED** [review]

**Comment by DStavilaNI** [comment]
One more feedback here : please make sure to check that the DMA configuration, for the remaining DMA channels, stays unchanged after reloading the bitfile. I think this check is not present in the current implementation of the DMA Test -> I mean looking out for these parameters:

image

See "DMA Channel.vi" in the SE.

**Comment by zszilagy** [comment]
> One more feedback here : please make sure to check that the DMA configuration, for the remaining DMA channels, stays unchanged after reloading the bitfile. I think this check is not present in the current implementation of the DMA Test -> I mean looking out for these parameters:
> 
> image
> 
> See "DMA Channel.vi" in the SE.

Added the requested verification.

**Comment by DStavilaNI** [comment]
> 
> 
> > One more feedback here : please make sure to check that the DMA configuration, for the remaining DMA channels, stays unchanged after reloading the bitfile. I think this check is not present in the current implementation of the DMA Test -> I mean looking out for these parameters:
> > image
> > See "DMA Channel.vi" in the SE.
> 
> Added the requested verification.

Nice implementation, just please make sure to check for the initial condition of the DMA settings, before loading the second bitfile

**Review by DStavilaNI — APPROVED** [review]
Seems good :)

**Pull request merged**
