### PR TITLE
Implement bitfile reload functionality

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds the "Refresh Bitfile" functionality to the Custom device.

### Why should this Pull Request be merged?

Currently, when a user loads an already configured bitfile which was recompiled, all the Scalar and DMA channels are automatically removed, even if these were not changed. This PR provides a solution for this problem by removing only the channels which were modified.

### What testing has been done?

Built the CD locally and it passed.
Loaded the CD in VS and performed manual testing to make sure that everything is functional and the feature works as expected.

### CODE REVIEW

**Comment by DStavilaNI** [comment]
I do have the following feedback regarding the implementation:

1. Consider the following implementation for Get Invalid Scalar Data Channels - simpler and easier to read:
       
image

2. I assume you are checking here for invalid references. However, I believe that the check that is done here is not enough. The actual invalid reference value, equals "18446744073709551615" or "FFFFFFFFFFFFFFFF". "0" is the reference value for the root element in SE ... you can keep this check, but the actual validation of a valid reference has to be implemented as well.  

image

3. In "Get Invalid DMA Configuration.vi" - I am not sure I understand what is the intended logic

image

a. If a DMA channel was already found in the old bitfile dma channels, then what is the point of creating another DMA channel with the same name ? 
b. If the datatypes are different, what is the point of creating a DMA Channel with the same name, if it already exists ? The "Create Waveform Channel.vi would not do anything". 
c. To be honest, I am not completely sure now, but at this point I think that the algorithm should be quite simple.  If the DMA channel was not found in SE, delete it. If it was found, then do not touch it - do not do anything. The bitfile registers will be overridden anyway with the new data, including the datatype. 

4. There are a lot of modified files in the tests directory - I would suggest to look through those, identify the files the were modified unnintentionally and revert them.

**Comment by DStavilaNI** [comment]
Looks good. I would probably recommend, after this PR is closed, to implement a unit test for the reloading functionality ... maybe a system test too.

**Review by DStavilaNI — APPROVED** [review]
[Recommended] - I would strongly advice to pay more attention to code styling, and generally following LabVIEW Coding Best practices

**Comment by bogdanp-ni** [comment]
Please update this VI icon to refer to DMA:
image

**Comment by bogdanp-ni** [comment]
Get Active Section Scalars - please refactor this VI in a follow-up PR. You should break it up into manageable subVIs. As it is right now, this VI has way too many logic levels in it and it is very hard to comprehend what it does.

**Review by bogdanp-ni — APPROVED** [review]
Just the icon fix and it's good to go.

**Pull request merged**
