### PR TITLE
System Level Tests for basic DMA Channels Testing

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implemented System Level Tests for basic DMA Channels Testing
- Fixed bug with copying built files to the proper VS CD Directory
- Potential bug with the VS Application - either engine or Gateway, when running two or more consecutive tests with the FPGA DMA based waveform channels

### Why should this Pull Request be merged?

Implementation for User Story [1022747](https://ni.visualstudio.com/DevCentral/_boards/board/t/ASW%20G%20Ecosystem/Work%20Items/?workitem=1022747)

### What testing has been done?
Testing done on the local DEV machine, and involving a cRIO-9039 target.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Just a heads-up: you'll need to pull from upstream after Calin's PR goes in, both of you changed FPGA Addon.lvproj

**Comment by bogdanp-ni** [comment]
Please include the target type in the bitfile name, it will be easier to track them when running on multiple FPGAs. It's something I realized just yesterday, at the team's talks.

**Comment by bogdanp-ni** [comment]
At this point, I would like to submit the tests without this workaround:
image

I'm hoping we'll have a good fix coming either from VS or from VS-testing-tools on this. And if not, we'll reconvene on this and likely do this workaround in FPGA Addon Test Class, instead of here, to cover all FPGA tests.

**Comment by bogdanp-ni** [comment]
test_Basic Waveform Read and Write - this can be removed:
image

**Comment by DStavilaNI** [comment]
> 
> 
> At this point, I would like to submit the tests without this workaround:
> image
> 
> I'm hoping we'll have a good fix coming either from VS or from VS-testing-tools on this. And if not, we'll reconvene on this and likely do this workaround in FPGA Addon Test Class, instead of here, to cover all FPGA tests.

I think, in this case it does not make to much sense to put it in the FPGA Addon test class ... Also, would it be enough to simple use the False case of the Case Structure instead of deleting the part?  That was actually the reason why I designed it as an option in the first place.

**Comment by bogdanp-ni** [comment]
> I think, in this case it does not make to much sense to put it in the FPGA Addon test class 
Can you elaborate on that? The way I see it, we might hit this snag with other FPGA tests, even if it's not something visible on our local machines.

> Also, would it be enough to simple use the False case of the Case Structure instead of deleting the part? That was actually the reason why I designed it as an option in the first place.
I saw your point there, but here is my reasoning: this is definitely a product issue and needs to be fixed in the product. The tests caught the issue, which is great, that's why we're writing them. When we get the product fix, these tests will act as regression tests for that fix.

I would like to add this workaround only when all other solutions (the product fix, the VS testing-tools fix) were rejected, or when the failing test (on the ATS) is becoming a roadblock for us. Until then, it is either a finished, working test, or a failing test that showcases an actual problem (depending on the results we get on the ATS).

**Comment by DStavilaNI** [comment]
> 
> 
> > I think, in this case it does not make to much sense to put it in the FPGA Addon test class
> 
> Can you elaborate on that? The way I see it, we might hit this snag with other FPGA tests, even if it's not something visible on our local machines.
> 
> > Also, would it be enough to simple use the False case of the Case Structure instead of deleting the part? That was actually the reason why I designed it as an option in the first place.
> > I saw your point there, but here is my reasoning: this is definitely a product issue and needs to be fixed in the product. The tests caught the issue, which is great, that's why we're writing them. When we get the product fix, these tests will act as regression tests for that fix.
> 
> I would like to add this workaround only when all other solutions (the product fix, the VS testing-tools fix) were rejected, or when the failing test (on the ATS) is becoming a roadblock for us. Until then, it is either a finished, working test, or a failing test that showcases an actual problem (depending on the results we get on the ATS).

Yes - I believe it would make sense to add it to the FPGA Addon Test Class once/if this workaround is actually accepted. If we add it, but it get rejected later on because we have an "official fix", it would mean modifying the class twice (second time to remove it). As it is, it's optional and can be easily switched on/off, depending on our needs.

**Comment by bogdanp-ni** [comment]
> > > I think, in this case it does not make to much sense to put it in the FPGA Addon test class
> > 
> > 
> > Can you elaborate on that? The way I see it, we might hit this snag with other FPGA tests, even if it's not something visible on our local machines.
> > > Also, would it be enough to simple use the False case of the Case Structure instead of deleting the part? That was actually the reason why I designed it as an option in the first place.
> > > I saw your point there, but here is my reasoning: this is definitely a product issue and needs to be fixed in the product. The tests caught the issue, which is great, that's why we're writing them. When we get the product fix, these tests will act as regression tests for that fix.
> > 
> > 
> > I would like to add this workaround only when all other solutions (the product fix, the VS testing-tools fix) were rejected, or when the failing test (on the ATS) is becoming a roadblock for us. Until then, it is either a finished, working test, or a failing test that showcases an actual problem (depending on the results we get on the ATS).
> 
> Yes - I believe it would make sense to add it to the FPGA Addon Test Class once/if this workaround is actually accepted. If we add it, but it get rejected later on because we have an "official fix", it would mean modifying the class twice (second time to remove it). As it is, it's optional and can be easily switched on/off, depending on our needs.

The way I see it, the best course of action is to NOT add it now, wait until we have an answer on the preferred solutions, and only then add it to FPGA Addon Test Class (and modify test classes and VIs, if needed) in a separate PR. Therefore, only one PR is needed, in the worst case. And if we already discarded the other solutions, then we know we'll be sticking to this workaround for good. 

To be more clear, I already agreed with the correctness of the workaround, but I disagree with the fact that we want to use it right now and I prefer waiting a little bit on the final decision.

**Comment by DStavilaNI** [comment]
> 
> 
> > > > I think, in this case it does not make to much sense to put it in the FPGA Addon test class
> > > 
> > > 
> > > Can you elaborate on that? The way I see it, we might hit this snag with other FPGA tests, even if it's not something visible on our local machines.
> > > > Also, would it be enough to simple use the False case of the Case Structure instead of deleting the part? That was actually the reason why I designed it as an option in the first place.
> > > > I saw your point there, but here is my reasoning: this is definitely a product issue and needs to be fixed in the product. The tests caught the issue, which is great, that's why we're writing them. When we get the product fix, these tests will act as regression tests for that fix.
> > > 
> > > 
> > > I would like to add this workaround only when all other solutions (the product fix, the VS testing-tools fix) were rejected, or when the failing test (on the ATS) is becoming a roadblock for us. Until then, it is either a finished, working test, or a failing test that showcases an actual problem (depending on the results we get on the ATS).
> > 
> > 
> > Yes - I believe it would make sense to add it to the FPGA Addon Test Class once/if this workaround is actually accepted. If we add it, but it get rejected later on because we have an "official fix", it would mean modifying the class twice (second time to remove it). As it is, it's optional and can be easily switched on/off, depending on our needs.
> 
> The way I see it, the best course of action is to NOT add it now, wait until we have an answer on the preferred solutions, and only then add it to FPGA Addon Test Class (and modify test classes and VIs, if needed) in a separate PR. Therefore, only one PR is needed, in the worst case. And if we already discarded the other solutions, then we know we'll be sticking to this workaround for good.
> 
> To be more clear, I already agreed with the correctness of the workaround, but I disagree with the fact that we want to use it right now and I prefer waiting a little bit on the final decision.

Is it acceptable then in this case that I leave the current implementation as it is, but simply disable the workaround (there is a boolean constant for that :) ) to run the tests without it (vanilla mode :) ) ?

**Comment by bogdanp-ni** [comment]
> Is it acceptable then in this case that I leave the current implementation as it is, but simply disable the workaround (there is a boolean constant for that :) ) to run the tests without it (vanilla mode :) ) ?

At this point, I am perfectly fine knowing that the test might fail on the test runner, and that's acceptable because it showcases a product issue. Since I don't see any point in submitting code that won't run (being gated by that boolean constant) and is not in the right location (which is FPGA Addon Test class), let's go ahead with the tests without the workaround. If you want, you can save the workaround in another branch, in your fork, (I suggest using branches instead of working directly in your master branch, like now) and we can revisit it later, if the product issue will not be addressed another way.

**Comment by DStavilaNI** [comment]
The changes for this PR will be merged manually into the master repository, to resolve conflicts

**Pull request merged**
