### PR TITLE
Refactor DMA Channel.vi

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Refactored the code inside the "Apply:Value Change" event case of the "DMA Channels.vi" into a single unit testable subVI called" Apply DMA Configuration.vi.

Also added two unit tests which verifies if the Input/Output channels are added correctly once the Apply event was triggered.

### Why should this Pull Request be merged?

Currently there are no unit tests which verifies the functionality of the Apply: Value Change event case code. Also, in its current form, it's hard to test the code as it is right now.

### What testing has been done?

Run the unit tests locally and they all passed.
Built the custom device locally, added in a system definition and performed the actions the PR changes in order to make sure that everything works as expected (as before the refactor)

### CODE REVIEW

**Comment by DStavilaNI** [comment]
Please add " Draft Pull Request" to the title of the PR ... makes it easier to read and differentiate from the "normal" PRs...

**Comment by DStavilaNI** [comment]
Some feedback, regarding the current stage:

1. The SysDef is referencing a bitfile which is situated in a public VS directory: "C:\Users\Public\Documents\National Instruments\NI VeriStand 2019\FPGA\PXIe-7867R.lvbitx" ... the SysDef can reference external files, but in this case those should be situated in the Assets folder of the respective test case.  I would recommend this to be a general practice. 
2. In the current implementation, with the known VS CD API bug, when run, the test vi does not throw the correct error. Currently, if you run the test, you get an error stating that the test fails because the equality assertion was not satisfied, however this is incorrect. The test vi should report the proper error (in this case that a file/VI was not found). I understand that this is due to how the JKI Test tools are implemented as well as the VS API. Still, the test should be implemented to account correctly for possible errors.

**Comment by bogdanp-ni** [comment]
CDS Loader.vi.png

What is CDS? Please rename

**Comment by bogdanp-ni** [comment]
There's no explanation in the PR Description about the workaround added, why it was needed, how it was implemented, other alternatives considered, etc.

**Pull request closed without merging**
