### PR TITLE
Update Readme.md dependencies that migrated to Custom Device Development Tools

### PR DESCRIPTION
**Pull request by phutanu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Updates Readme.md with correct dependencies.

### Why should this Pull Request be merged?

- To help users not get confused by wrong/archived dependencies.

### What testing has been done?

- N/A

### CODE REVIEW

**Review by bogdanp-ni — APPROVED** [review]

**Review by DStavilaNI — COMMENTED** [review]
image

I think that this paragraph can be removed altogether since this action is not required and might be misleading for the user (maybe it was required at some point in the past). After formatting and installing the required software packages on the target, no other actions are necessary for deployment.

**Comment by DStavilaNI** [comment]
I think that the highlighted elements can be removed from the list, as these are already listed as dependencies for the NI VeriStand Custom Device Development Tools and and should be installed with them, not separately.  

image

**Comment by DStavilaNI** [comment]
I think that these should be links as well, to improve the user experience:

image

**Comment by phutanu** [comment]
> image
> 
> I think that this paragraph can be removed altogether since this action is not required and might be misleading for the user (maybe it was required at some point in the past). After formatting and installing the required software packages on the target, no other actions are necessary for deployment.

Implemented.

**Comment by phutanu** [comment]
> I think that the highlighted elements can be removed from the list, as these are already listed as dependencies for the NI VeriStand Custom Device Development Tools and and should be installed with them, not separately.
> 
> image

Implemented.

**Comment by phutanu** [comment]
> I think that these should be links as well, to improve the user experience:
> 
> image

Implemented.

**Comment by phutanu** [comment]
@DStavilaNI Kind reminder.

**Review by DStavilaNI — APPROVED** [review]

**Pull request merged**
