### PR TITLE
Added the "Refresh bitfile functionality to the FPGA Addon Custom device

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds the "Refresh Bitfile" functionality to the Custom device.

### Why should this Pull Request be merged?

Currently, when a user loads an already configured bitfile which was recompiled, all the Scalar and DMA channels are automatically removed, even if these were not changed. This PR provides a solution for this problem by removing only the channels which were modified.

### What testing has been done?

Built the CD locally and it passed. 
Loaded the CD in VS and performed manual testing to make sure that everything is functional and the feature works as expected.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Reload Bitfile.vi -> the VI is rather difficult to read due to duplicated code (when it comes to filtering out invalid registers, which can be hidden away into a subVI that gets called twice): 
image

Same goes for waveforms.

**Comment by bogdanp-ni** [comment]
Please add tests for this change, in a follow-up PR.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
Just the refactoring part to be done, otherwise the change is ready to go.

**Comment by bogdanp-ni** [comment]
There's a weird overlap of wires here - please fix before submitting:
image

**Comment by bogdanp-ni** [comment]
Reload Bitfile.vi -> please add a "theory of operation" comment explaining it.

**Review by bogdanp-ni — APPROVED** [review]
Just two minor fixes to be done (see comments).

**Comment by DStavilaNI** [comment]
Hello, I have a bunch o comments regarding this PR:

1. When checking for invalid scalars, DMAs etc., you are checking everything by name, if it still exists or not in the bitfile ( for example in "Get Invalid Scalar Data Channels.vi"). What happens if the name/label is the same, but the data-type was changed ? The old bitfile object references become invalid and this will lead to errors.

2.  In the SE, in the "Main Page.vi", in both "Refresh Bitfile: Value Change" and "Bitfile Path: Value Change" event cases, the same "Reload Bitfile.vi" is being used. If I change to a different bitfile (Bitfile Path: Value Change), and since the "Reload Bitfile.vi" will be called - the old configuration will not be automatically cleared (as it was done before) and this might lead to a lot of conflicts: for example if the new bitfile will have scalars with the same names as the old one, but different data-types. Generally, a very useful check would be to see if the newly loaded bitfile has a different name/path compared to the one previously stored. If the bitfile name is different, assume it is a different bitfile, and clear the entire configuration - no need to check for bitfile objects.

3. I am not sure these "Case Structures" are making sense, since in both their cases, the same VI is being called: 
 - image
 - image

4. When removing an item (be it a scalar channel or DMA channel), the assumption is being made that the object bitfile name is the same as the channel name in the SE.

image

This might not be the case, since the "Name" field for a channel is editable. 

image

I would recommend to check for the object bitfile name. 

5. [Recommended] There is a lot of duplicated code:
  - "Refresh Scalar Channels.vi" is basically identical to the "Refresh Waveform Channels.vi" -> the only difference is the input array of clusters. From these clusters, you are only using the "Name" field in both cases. For example, it would make much more sense (imho) to simply pass to these subVIs, an array of strings, since, essentially the same operations are being performed. 
  - The above observation is valid for both "Get Invalid Scalar Channels.vi" and "Get Invalid DMA Configurations.vi". 
  
  
image

and

image

**Comment by bogdanp-ni** [comment]
> 2. In the SE, in the "Main Page.vi", in both "Refresh Bitfile: Value Change" and "Bitfile Path: Value Change" event cases, the same "Reload Bitfile.vi" is being used. If I change to a different bitfile (Bitfile Path: Value Change), and since the "Reload Bitfile.vi" will be called - the old configuration will not be automatically cleared (as it was done before) and this might lead to a lot of conflicts: for example if the new bitfile will have scalars with the same names as the old one, but different data-types. Generally, a very useful check would be to see if the newly loaded bitfile has a different name/path compared to the one previously stored. If the bitfile name is different, assume it is a different bitfile, and clear the entire configuration - no need to check for bitfile objects.

I still believe we must not clear all settings previously made for a different bitfile when loading a new bitfile. There is a prevalent use-case where multiple compiles of the same FPGA VI are needed (hence, multiple buildspecs are used => multiple bitfiles) and the user might load one of them, configure the FPGA Addon, then load another bitfile. In fact, the reload algorithm should be fine when a bitfile with a totally different set of controls/indicators/DMAs is loaded and will remove all previous configs. Therefore, the persistence of FPGA Addon settings must be done for both "load (new/same) bitfile" and "refresh bitfile" options, in my opinion.

@cheloizaguirre would you be able to share an opinion on this?

**Comment by DStavilaNI** [comment]
> 
> 
> > 1. In the SE, in the "Main Page.vi", in both "Refresh Bitfile: Value Change" and "Bitfile Path: Value Change" event cases, the same "Reload Bitfile.vi" is being used. If I change to a different bitfile (Bitfile Path: Value Change), and since the "Reload Bitfile.vi" will be called - the old configuration will not be automatically cleared (as it was done before) and this might lead to a lot of conflicts: for example if the new bitfile will have scalars with the same names as the old one, but different data-types. Generally, a very useful check would be to see if the newly loaded bitfile has a different name/path compared to the one previously stored. If the bitfile name is different, assume it is a different bitfile, and clear the entire configuration - no need to check for bitfile objects.
> 
> I still believe we must not clear all settings previously made for a different bitfile when loading a new bitfile. There is a prevalent use-case where multiple compiles of the same FPGA VI are needed (hence, multiple buildspecs are used => multiple bitfiles) and the user might load one of them, configure the FPGA Addon, then load another bitfile. In fact, the reload algorithm should be fine when a bitfile with a totally different set of controls/indicators/DMAs is loaded and will remove all previous configs. Therefore, the persistence of FPGA Addon settings must be done for both "load (new/same) bitfile" and "refresh bitfile" options, in my opinion.
> 
> @cheloizaguirre would you be able to share an opinion on this?

I strongly disagree. More specifically:

1. "**I still believe we must not clear all settings previously made for a different bitfile when loading a new bitfile.**" - You are making the assumption that when selecting a new bitfile, with a different name, it will always be a modified version of the previous one - is it correct ? And when I say "modified", I mean that the I/Os are essentially the same and only the logic is changed. I think that would be a rather big assumption. The code, as it is, certainly does not have any verification or protection mechanism to check for that. 
2. "**There is a prevalent use-case where multiple compiles of the same FPGA VI are needed (hence, multiple buildspecs are used => multiple bitfiles) and the user might load one of them, configure the FPGA Addon, then load another bitfile.**" - I agree that such use-case exists and some people are doing development this way. I am not sure though that it makes sense to build/change the functionality of the FPGA Addon around a single use-case. Additionally, as mentioned in the point above, again the assumption that different versions of a given bitfile will have the same IO structure (control/DMA names and datatypes), is made here.
3. "In fact, the reload algorithm should be fine when a bitfile with a totally different set of controls/indicators/DMAs is loaded and will remove all previous configs." - true. However, to be more specific, I think that the reload algorithm will ONLY be fine in this particular case. If for example  I load a "Bitfile1" with "Scalar1" control of "Int32" type, then load the "Bitfile2" also with a "Scalar1" control, but with "DBL" type, the algorithm, as it is, will not differentiate between the two controls, since the names are the same. This will generate errors after deployment, and during execution, since essentially a "Int32" ref will be used for a "DBL" type.   

As a side question - did anyone do any testing in this regard and for these situations ?

**Comment by zszilagy** [comment]
> When checking for invalid scalars, DMAs etc., you are checking everything by name, if it still exists or not in the bitfile ( for example in "Get Invalid Scalar Data Channels.vi"). What happens if the name/label is the same, but the data-type was changed ? The old bitfile object references become invalid and this will lead to errors.

Indeed this caused the SE to freeze up. It was resolved by adding the channel to the "invalid channels" list if one of the following property has been changed during recompilation:
 -input/output name
-data type
-default value

**Comment by zszilagy** [comment]
> I am not sure these "Case Structures" are making sense, since in both their cases, the same VI is being called:

image
image

These cases are obsolete. It remained there from a previous implementation. They were removed

**Comment by cheloizaguirre** [comment]
> > 1. In the SE, in the "Main Page.vi", in both "Refresh Bitfile: Value Change" and "Bitfile Path: Value Change" event cases, the same "Reload Bitfile.vi" is being used. If I change to a different bitfile (Bitfile Path: Value Change), and since the "Reload Bitfile.vi" will be called - the old configuration will not be automatically cleared (as it was done before) and this might lead to a lot of conflicts: for example if the new bitfile will have scalars with the same names as the old one, but different data-types. Generally, a very useful check would be to see if the newly loaded bitfile has a different name/path compared to the one previously stored. If the bitfile name is different, assume it is a different bitfile, and clear the entire configuration - no need to check for bitfile objects.
> 
> I still believe we must not clear all settings previously made for a different bitfile when loading a new bitfile. There is a prevalent use-case where multiple compiles of the same FPGA VI are needed (hence, multiple buildspecs are used => multiple bitfiles) and the user might load one of them, configure the FPGA Addon, then load another bitfile. In fact, the reload algorithm should be fine when a bitfile with a totally different set of controls/indicators/DMAs is loaded and will remove all previous configs. Therefore, the persistence of FPGA Addon settings must be done for both "load (new/same) bitfile" and "refresh bitfile" options, in my opinion.
> 
> @cheloizaguirre would you be able to share an opinion on this?

I agree with these statements. The refresh functionality is intended to serve users who want to use the same CD item in the tree. The main reason would be to preserve mappings and configuration previously done. If they want to start from scratch, that's what adding a new CD is for. Even if the file name or anything else is different, we should attempt to preserve as much configuration as possible. 

As for this comment from @DStavilaNI:
> If for example I load a "Bitfile1" with "Scalar1" control of "Int32" type, then load the "Bitfile2" also with a "Scalar1" control, but with "DBL" type, the algorithm, as it is, will not differentiate between the two controls, since the names are the same. This will generate errors after deployment, and during execution, since essentially a "Int32" ref will be used for a "DBL" type.
"Scalar1" is never "Scalar1." It's "EngineTemp" or "RPM". If the user already told us that they care about "RPM" we should do everything we can to keep "RPM" in the reloaded configuration. If it used to be i32 and now it's DBL, then let's make their lives easier and convert that old i32 to a DBL.

**Comment by DStavilaNI** [comment]
> 
> 
> > I still believe we must not clear all settings previously made for a different bitfile when loading a new bitfile. There is a prevalent use-case where multiple compiles of the same FPGA VI are needed (hence, multiple buildspecs are used => multiple bitfiles) and the user might load one of them, configure the FPGA Addon, then load another bitfile. In fact, the reload algorithm should be fine when a bitfile with a totally different set of controls/indicators/DMAs is loaded and will remove all previous configs. Therefore, the persistence of FPGA Addon settings must be done for both "load (new/same) bitfile" and "refresh bitfile" options, in my opinion.
> > @cheloizaguirre would you be able to share an opinion on this?
> 
> I agree with these statements. The refresh functionality is intended to serve users who want to use the same CD item in the tree. The main reason would be to preserve mappings and configuration previously done. If they want to start from scratch, that's what adding a new CD is for. Even if the file name or anything else is different, we should attempt to preserve as much configuration as possible.
> 
> As for this comment from @DStavilaNI:
> 
> > If for example I load a "Bitfile1" with "Scalar1" control of "Int32" type, then load the "Bitfile2" also with a "Scalar1" control, but with "DBL" type, the algorithm, as it is, will not differentiate between the two controls, since the names are the same. This will generate errors after deployment, and during execution, since essentially a "Int32" ref will be used for a "DBL" type.
> 
> "Scalar1" is never "Scalar1." It's "EngineTemp" or "RPM". If the user already told us that they care about "RPM" we should do everything we can to keep "RPM" in the reloaded configuration. If it used to be i32 and now it's DBL, then let's make their lives easier and convert that old i32 to a DBL.

There was never a question about refreshing. My comment there was simply that the code does not check for datatype changes, and for me that is a big assumption. 

My issue is rather with loading a new bitfile - so, essentially, here, Marcelo, you are saying "Don't worry about it, just delete the old and create a new FPGA Addon CD" ... but why, or how is this elegant or user-friendly ? Most of the software out-there is asking the user "Hey, I can see you are unloading and loading something else - do you want to keep the current configuration of do you want to reset it ?". The other option could be that there is a check-mark next to the path control to the bitfile, where you set this as an option. And if we really want to keep everything in the background, we at least check for changes in the control names and datatypes when we load/reload any bitfile against the existing structure in the SE. It's pretty much common sense - you cannot blindly load a bitfile and assume that everything (in terms of IOs) will be the  same ...

**Comment by zszilagy** [comment]
>4. When removing an item (be it a scalar channel or DMA channel), the assumption is being made that the object bitfile name is the same as the channel name in the SE.

This behavior was tested and renaming the channel in the SE doesn't have any effect on the functionality of the reload. The name in the above mentioned cases in fact referring to the bitfile name and not to the display name in the SE.

**Comment by DStavilaNI** [comment]
> 
> 
> > 1. When removing an item (be it a scalar channel or DMA channel), the assumption is being made that the object bitfile name is the same as the channel name in the SE.
> 
> This behavior was tested and renaming the channel in the SE doesn't have any effect on the functionality of the reload. The name in the above mentioned cases in fact referring to the bitfile name and not to the display name in the SE.

We tested it together with Zoli, and the bug is still there. Some refactoring will be required in the current implementation.

**Comment by zszilagy** [comment]
Messed up the some commits in this PR. Closing as a clean new one was created here: https://github.com/ni/niveristand-fpga-addon-custom-device/pull/65

**Pull request closed without merging**
