### PR TITLE
Scripting API Unit Tests Fix

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Scripting API Unit Tests fix/update for the new version ofthe FPGA  Addon with extended FXP support.

### Why should this Pull Request be merged?

- Release finalization for the Extended FXP support 

### What testing has been done?

- Local testing has been done

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
FPGA Addon Scripting API Unit Tests.lvclass--test_Get Bitfile Scalars_Error.vi -> if no changes, please revert

**Comment by bogdanp-ni** [comment]
FPGA Addon Scripting API Unit Tests.lvclass--test_Set FPGA Bitfile_Error.vi -> same here

**Comment by bogdanp-ni** [comment]
Scripting API.lvlib--Import Scalars - by label.vi -> same here

**Review by bogdanp-ni — APPROVED** [review]
Approved, but please make sure that files with no changes are not submitted.

I usually insist on this and believe keeping a clean file history is important. Being binary files, it is impossible to see the changes in detail, like for a text file. Therefore, we rely on diffing tools to tell us the changes that were made. If Git detects a change and our diffing tool does not, then there's no way of actually reviewing/understanding the change, hence it may very well be an unwanted change. That may very well be a problem with our diffing tools, that's why I'm always asking if an "invisible change" was actually intended (and found by git, but not by our diffing tools).

**Comment by DStavilaNI** [comment]
> 
> 
> FPGA Addon Scripting API Unit Tests.lvclass--test_Get Bitfile Scalars_Error.vi -> if no changes, please revert

Done

**Comment by DStavilaNI** [comment]
> 
> 
> FPGA Addon Scripting API Unit Tests.lvclass--test_Set FPGA Bitfile_Error.vi -> same here

Done

**Comment by DStavilaNI** [comment]
> 
> 
> Scripting API.lvlib--Import Scalars - by label.vi -> same here

This file was actually changed

**Pull request merged**
