### PR TITLE
Migration of all the System Test Assets to the ATS HW configuration

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Separated compiled code for all of the project VIs
- Migrated remaining Asset code to LV2018
- Migrated all of the System Test Assets to the ATS HW Configuration
- Merged changes from the PR of Paul -> added the Generic Unit Tests

### Why should this Pull Request be merged?

- Migrated all of the System Test Assets to the ATS HW Configuration -> preparation for ATS test runs

### What testing has been done?

- Local run of the test VIs
- Local Build of the FPGA Addon

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml

**Comment by bogdanp-ni** [comment]
I would like us to keep both cRIO and R Series bitfiles available in the Assets folders. According to the GitHub diff, the bitfiles were renamed, which I know is not the case, so I'm guessing you deleted the cRIO ones and added the R Series in place.

**Comment by bogdanp-ni** [comment]
Please make sure the vs-testing-tools dependency is loaded not from vi.lib, but from a folder in the same hierarchy as the cloned repo folder. This is the expected format on the ATS machines.

**Comment by DStavilaNI** [comment]
> 
> 
> Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml

I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project.  The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.

**Comment by DStavilaNI** [comment]
> 
> 
> I would like us to keep both cRIO and R Series bitfiles available in the Assets folders. According to the GitHub diff, the bitfiles were renamed, which I know is not the case, so I'm guessing you deleted the cRIO ones and added the R Series in place.

It is true. I did delete the old cRIO bitfiles - I did not think/know it is necessary to keep them in the project any longer. In case we need those, however, I think we can simply checkout a commit prior to the back-porting or transition to the ATS hardware configuration.  Would that be a solution ?

**Comment by bogdanp-ni** [comment]
> > I would like us to keep both cRIO and R Series bitfiles available in the Assets folders. According to the GitHub diff, the bitfiles were renamed, which I know is not the case, so I'm guessing you deleted the cRIO ones and added the R Series in place.
> 
> It is true. I did delete the old cRIO bitfiles - I did not think/know it is necessary to keep them in the project any longer. In case we need those, however, I think we can simply checkout a commit prior to the back-porting or transition to the ATS hardware configuration. Would that be a solution ?

I find that to be very cumbersome. One would have to know where to look in the history to find those files. My reasoning for keeping the bitfiles is that it gives us the ability to run tests locally, on our cRIO.

**Comment by bogdanp-ni** [comment]
> > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> 
> I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.

No worries. A clean revert on the file will do the trick, then.

**Comment by phutanu** [comment]
> > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > 
> > 
> > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> 
> No worries. A clean revert on the file will do the trick, then.

The XML file will show as been changed each time you run the "test_Connector Pane.vi".

**Comment by DStavilaNI** [comment]
> 
> 
> > > I would like us to keep both cRIO and R Series bitfiles available in the Assets folders. According to the GitHub diff, the bitfiles were renamed, which I know is not the case, so I'm guessing you deleted the cRIO ones and added the R Series in place.
> > 
> > 
> > It is true. I did delete the old cRIO bitfiles - I did not think/know it is necessary to keep them in the project any longer. In case we need those, however, I think we can simply checkout a commit prior to the back-porting or transition to the ATS hardware configuration. Would that be a solution ?
> 
> I find that to be very cumbersome. One would have to know where to look in the history to find those files. My reasoning for keeping the bitfiles is that it gives us the ability to run tests locally, on our cRIO.

We can still run tests locally, since currently those are configured for the GEcosystemPharlap, which, to my knowledge, is a PXI system in our office.

**Comment by DStavilaNI** [comment]
> 
> 
> > > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > > 
> > > 
> > > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> > 
> > 
> > No worries. A clean revert on the file will do the trick, then.
> 
> The XML file will show as been changed each time you run the "test_Connector Pane.vi".

That explains it then ;)

**Comment by phutanu** [comment]
> > > > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > > > 
> > > > 
> > > > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> > > 
> > > 
> > > No worries. A clean revert on the file will do the trick, then.
> > 
> > 
> > The XML file will show as been changed each time you run the "test_Connector Pane.vi".
> 
> That explains it then ;)



> > > > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > > > 
> > > > 
> > > > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> > > 
> > > 
> > > No worries. A clean revert on the file will do the trick, then.
> > 
> > 
> > The XML file will show as been changed each time you run the "test_Connector Pane.vi".
> 
> That explains it then ;)

But we do not commit the changed file by the test itself. Just to avoid any unintended behavior caused by this.

**Comment by DStavilaNI** [comment]
> 
> 
> Please make sure the vs-testing-tools dependency is loaded not from vi.lib, but from a folder in the same hierarchy as the cloned repo folder. This is the expected format on the ATS machines.

I think this should be a separate PR, and it was not the target of the current work/commit. We did discuss it during one of our team meetings that it should be tackled independently, as part of the preparation for the deployment on the ATS.

**Comment by DStavilaNI** [comment]
> 
> 
> > > > > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > > > > 
> > > > > 
> > > > > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> > > > 
> > > > 
> > > > No worries. A clean revert on the file will do the trick, then.
> > > 
> > > 
> > > The XML file will show as been changed each time you run the "test_Connector Pane.vi".
> > 
> > 
> > That explains it then ;)
> 
> But we do not commit the changed file by the test itself. Just to avoid any unintended behavior caused by this.

Sure, but is it a problem ? The builds are running properly. The file is marked as modified, but is not actually changed.

**Comment by phutanu** [comment]
> > > > > > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > > > > > 
> > > > > > 
> > > > > > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> > > > > 
> > > > > 
> > > > > No worries. A clean revert on the file will do the trick, then.
> > > > 
> > > > 
> > > > The XML file will show as been changed each time you run the "test_Connector Pane.vi".
> > > 
> > > 
> > > That explains it then ;)
> > 
> > 
> > But we do not commit the changed file by the test itself. Just to avoid any unintended behavior caused by this.
> 
> Sure, but is it a problem ? The builds are running properly. The file is marked as modified, but is not actually changed.

It is not a safe practice to submit unintended file changes. We will not know if it is a problem, until we will run into one.

**Comment by bogdanp-ni** [comment]
> > > > > > > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > > > > > > 
> > > > > > > 
> > > > > > > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> > > > > > 
> > > > > > 
> > > > > > No worries. A clean revert on the file will do the trick, then.
> > > > > 
> > > > > 
> > > > > The XML file will show as been changed each time you run the "test_Connector Pane.vi".
> > > > 
> > > > 
> > > > That explains it then ;)
> > > 
> > > 
> > > But we do not commit the changed file by the test itself. Just to avoid any unintended behavior caused by this.
> > 
> > 
> > Sure, but is it a problem ? The builds are running properly. The file is marked as modified, but is not actually changed.
> 
> It is not a safe practice to submit unintended file changes. We will not know if it is a problem, until we will run into one.

I agree. Altering a file should be done only when that alteration is intended and understood, even if it just means the formatting has changed.

**Comment by bogdanp-ni** [comment]
> > Please make sure the vs-testing-tools dependency is loaded not from vi.lib, but from a folder in the same hierarchy as the cloned repo folder. This is the expected format on the ATS machines.
> 
> I think this should be a separate PR, and it was not the target of the current work/commit. We did discuss it during one of our team meetings that it should be tackled independently, as part of the preparation for the deployment on the ATS.

I'm fine with having a second PR, as a follow-up on the current, to fix the dependency. If possible, I would like it tackled as soon as possible, so we can have test results by tomorrow.

**Comment by bogdanp-ni** [comment]
> > > > I would like us to keep both cRIO and R Series bitfiles available in the Assets folders. According to the GitHub diff, the bitfiles were renamed, which I know is not the case, so I'm guessing you deleted the cRIO ones and added the R Series in place.
> > > 
> > > 
> > > It is true. I did delete the old cRIO bitfiles - I did not think/know it is necessary to keep them in the project any longer. In case we need those, however, I think we can simply checkout a commit prior to the back-porting or transition to the ATS hardware configuration. Would that be a solution ?
> > 
> > 
> > I find that to be very cumbersome. One would have to know where to look in the history to find those files. My reasoning for keeping the bitfiles is that it gives us the ability to run tests locally, on our cRIO.
> 
> We can still run tests locally, since currently those are configured for the GEcosystemPharlap, which, to my knowledge, is a PXI system in our office.

I still don't see the downside in keeping the old bitfiles.

**Comment by DStavilaNI** [comment]
> 
> 
> > > > > > > > > Why was the XML modified? Source/Addon/Custom Device FPGA Addon.xml
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I think this is an artifact of the migration process itself -> I cannot fully explain it, but I believe it "manifested" after I separated the compiled code for all of the VIs within the project. The xml file itself, the content, is not modified. The build process is running without issues and the FPGA CD is generated properly.
> > > > > > > 
> > > > > > > 
> > > > > > > No worries. A clean revert on the file will do the trick, then.
> > > > > > 
> > > > > > 
> > > > > > The XML file will show as been changed each time you run the "test_Connector Pane.vi".
> > > > > 
> > > > > 
> > > > > That explains it then ;)
> > > > 
> > > > 
> > > > But we do not commit the changed file by the test itself. Just to avoid any unintended behavior caused by this.
> > > 
> > > 
> > > Sure, but is it a problem ? The builds are running properly. The file is marked as modified, but is not actually changed.
> > 
> > 
> > It is not a safe practice to submit unintended file changes. We will not know if it is a problem, until we will run into one.
> 
> I agree. Altering a file should be done only when that alteration is intended and understood, even if it just means the formatting has changed.

Ok guys, you won. I will put it back.

**Comment by DStavilaNI** [comment]
> 
> 
> > > > > I would like us to keep both cRIO and R Series bitfiles available in the Assets folders. According to the GitHub diff, the bitfiles were renamed, which I know is not the case, so I'm guessing you deleted the cRIO ones and added the R Series in place.
> > > > 
> > > > 
> > > > It is true. I did delete the old cRIO bitfiles - I did not think/know it is necessary to keep them in the project any longer. In case we need those, however, I think we can simply checkout a commit prior to the back-porting or transition to the ATS hardware configuration. Would that be a solution ?
> > > 
> > > 
> > > I find that to be very cumbersome. One would have to know where to look in the history to find those files. My reasoning for keeping the bitfiles is that it gives us the ability to run tests locally, on our cRIO.
> > 
> > 
> > We can still run tests locally, since currently those are configured for the GEcosystemPharlap, which, to my knowledge, is a PXI system in our office.
> 
> I still don't see the downside in keeping the old bitfiles.

There is no downside, it's just that they are useless with the current configurations of the SysDefs. Also, it will mean spending time to recover them and put them back - still, in this case I will go ahead and re-add them.

**Pull request merged**
