### PR TITLE
Bundle shared dependencies in order to fix namespace issues with other Custom Devices

### PR DESCRIPTION
**Pull request by phutanu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Adds two virtual folders for each Target in the LabVIEW project:
    - NI VeriStand APIs - that contains the VeriStand APIs
    - Bundled Dependencies - that contains shared dependencies

### Why should this Pull Request be merged?

- This change is required in order to fix namespace issues with other Custom Devices during deployment.

### What testing has been done?

- The Custom Device has been built using LabVIEW 2019 and deployed on a clean Virtual Machine with VeriStand 2019 R3 in order to validate that OPAL-RT Power Electronics Addon and FPGA Addon can deploy successfully on a PharLap Target. 

### As the diff bot does not generate visual for .lvproj file changes, here are some snips:

NI VeriStand APIs settings:
VeriStand APIs

Bundled Dependencies settings:
Bundled Dependencies

### CODE REVIEW

**Review by bogdanp-ni — APPROVED** [review]

**Comment by DStavilaNI** [comment]
I would have some questions related to the NI VeriStand API -> specifically why was it included in the project and the build specs modified for it ?  If I understood correctly, the problem was related only to the VeriStand Development Tools packages and the fix is about prefixing all it's contained items. This was not the case for the NI VeriStand API and I would like to understand the reasoning behind it.

**Comment by phutanu** [comment]
> I would have some questions related to the NI VeriStand API -> specifically why was it included in the project and the build specs modified for it ? If I understood correctly, the problem was related only to the VeriStand Development Tools packages and the fix is about prefixing all it's contained items. This was not the case for the NI VeriStand API and I would like to understand the reasoning behind it.

The `NI VeriStand APIs` were already present in the `.lvproj` in the Dependencies section. During the investigation, I tried to also prefix and bundle them, but VeriStand does not like that. So, as a precaution, I made a virtual folder and add them there just for other developers to know that these dependencies should not be modified/changed/added elsewhere.

This is the same implementation as in `Routing and Faulting Custom Device`.

**Comment by DStavilaNI** [comment]
> 
> 
> > I would have some questions related to the NI VeriStand API -> specifically why was it included in the project and the build specs modified for it ? If I understood correctly, the problem was related only to the VeriStand Development Tools packages and the fix is about prefixing all it's contained items. This was not the case for the NI VeriStand API and I would like to understand the reasoning behind it.
> 
> The `NI VeriStand APIs` were already present in the `.lvproj` in the Dependencies section. During the investigation, I tried to also prefix and bundle them, but VeriStand does not like that. So, as a precaution, I made a virtual folder and add them there just for other developers to know that these dependencies should not be modified/changed/added elsewhere.
> 
> This is the same implementation as in `Routing and Faulting Custom Device`.

I agree that NI VeriStand APIs exist already in the Dependencies section - as I assume is the case with all VS CDs, and it only makes sense that those cannot be modified as you described. I am still not sure it makes sense to add them to the project explicitly - it seems like an unnecessary change.

**Comment by phutanu** [comment]
> > > I would have some questions related to the NI VeriStand API -> specifically why was it included in the project and the build specs modified for it ? If I understood correctly, the problem was related only to the VeriStand Development Tools packages and the fix is about prefixing all it's contained items. This was not the case for the NI VeriStand API and I would like to understand the reasoning behind it.
> > 
> > 
> > The `NI VeriStand APIs` were already present in the `.lvproj` in the Dependencies section. During the investigation, I tried to also prefix and bundle them, but VeriStand does not like that. So, as a precaution, I made a virtual folder and add them there just for other developers to know that these dependencies should not be modified/changed/added elsewhere.
> > This is the same implementation as in `Routing and Faulting Custom Device`.
> 
> I agree that NI VeriStand APIs exist already in the Dependencies section - as I assume is the case with all VS CDs, and it only makes sense that those cannot be modified as you described. I am still not sure it makes sense to add them to the project explicitly - it seems like an unnecessary change.

As previously mentioned, I used the same implementation as the one for `Routing and Faulting Custom Device`, as this is our reference for solving namespace issues.

We can add Ryan Zoeller to the thread, if you want, and discuss more if the `NI VeriStand APIs` virtual folder is really needed or not.

If we decide to remove the `NI VeriStand APIs` virtual folder, then I would require additional time to test that removing this virtual folder does not break deployment when other Custom Devices (e.g. OPAL RT's PE Addon) are present in the System Definition.

**Comment by DStavilaNI** [comment]
> 
> 
> > > > I would have some questions related to the NI VeriStand API -> specifically why was it included in the project and the build specs modified for it ? If I understood correctly, the problem was related only to the VeriStand Development Tools packages and the fix is about prefixing all it's contained items. This was not the case for the NI VeriStand API and I would like to understand the reasoning behind it.
> > > 
> > > 
> > > The `NI VeriStand APIs` were already present in the `.lvproj` in the Dependencies section. During the investigation, I tried to also prefix and bundle them, but VeriStand does not like that. So, as a precaution, I made a virtual folder and add them there just for other developers to know that these dependencies should not be modified/changed/added elsewhere.
> > > This is the same implementation as in `Routing and Faulting Custom Device`.
> > 
> > 
> > I agree that NI VeriStand APIs exist already in the Dependencies section - as I assume is the case with all VS CDs, and it only makes sense that those cannot be modified as you described. I am still not sure it makes sense to add them to the project explicitly - it seems like an unnecessary change.
> 
> As previously mentioned, I used the same implementation as the one for `Routing and Faulting Custom Device`, as this is our reference for solving namespace issues.
> 
> We can add Ryan Zoeller to the thread, if you want, and discuss more if the `NI VeriStand APIs` virtual folder is really needed or not.
> 
> If we decide to remove the `NI VeriStand APIs` virtual folder, then I would require additional time to test that removing this virtual folder does not break deployment when other Custom Devices (e.g. OPAL RT's PE Addon) are present in the System Definition.

Hey Paul, thank you for your reply. Since this is your PR and not Ryan's, my questions is addressed to you - otherwise, I would have asked him just as well. Please feel free to discuss this with him if necessary. I am generally interested in finding out the reasons behind these kind of changes as opposed to simply reusing other implementations without proper validation.

I can tell you that the "NI VeriStand API" is by default included in the VS CD template project, however, as you know, the API itself is still located in vi.lib, in the LabVIEW directory. The same API is available through the LabVIEW palettes ... now, at this point I do not know why is this API still included in the LabVIEW CD template project (I assume that the template project was created before the API became available through the LV palettes and then things stayed that way), however this API was not previously part of the FPGA Addon project. Unless it solves a specific problem, I would prefer for it to be removed since it would unnecessarily clutter the project tree. That being said, if there is a valid reason for keeping things this way, I would agree with the changes.

Regarding testing - I would say that the counter argument would be that testing should have been done before the NI VeriStand API is included in the project structure  - that is, only with the bundled and prefixed dependencies, and add the extra project items if that testing would have failed. To put it in other words, only if proven that it actually helps.  

I am looking forward for your reply.
Denis

**Comment by phutanu** [comment]
Hey Denis,

I already explained above the reasoning behind adding them: to make a clear distinction in the project tree between the NI VeriStand shipping APIs and other dependencies. As we should not bundle and prefix the NI VeriStand ones.

Considering your strong desire to get rid of this Virtual Folder, I will remove it and restart the validation process for compatibility with OPAL-RT PE Addon.

**Comment by phutanu** [comment]
Removed `NI VeriStand APIs` virtual folder and validated that FPGA Addon is still compatible with OPAL RT PE Addon on PharLap Targets.

**Comment by DStavilaNI** [comment]
> 
> 
> Hey Denis,
> 
> I already explained above the reasoning behind adding them: to make a clear distinction in the project tree between the NI VeriStand shipping APIs and other dependencies. As we should not bundle and prefix the NI VeriStand ones.
> 
> Considering your strong desire to get rid of this Virtual Folder, I will remove it and restart the validation process for compatibility with OPAL-RT PE Addon.

Hey Paul,

Thank you for the reply and the feedback. 

Regarding the NI VeriStand shipping APIs - I believe that there is one more Bundled dependency that should be removed:

image

It seems like this library is also part of the VS shipping API and it should not affect/contribute to the dependencies issue - has this somehow been tested ?

I am looking forward for your reply,
Sincerely yours,
Denis

**Comment by phutanu** [comment]
> > Hey Denis,
> > I already explained above the reasoning behind adding them: to make a clear distinction in the project tree between the NI VeriStand shipping APIs and other dependencies. As we should not bundle and prefix the NI VeriStand ones.
> > Considering your strong desire to get rid of this Virtual Folder, I will remove it and restart the validation process for compatibility with OPAL-RT PE Addon.
> 
> Hey Paul,
> 
> Thank you for the reply and the feedback.
> 
> Regarding the NI VeriStand shipping APIs - I believe that there is one more Bundled dependency that should be removed:
> 
> image
> 
> It seems like this library is also part of the VS shipping API and it should not affect/contribute to the dependencies issue - has this somehow been tested ?
> 
> I am looking forward for your reply,
> Sincerely yours,
> Denis

Removed `Internal Comm Classes.lvlib` from Bundled Dependencies and validated that FPGA Addon is still compatible with OPAL RT PE Addon on PharLap Targets.

**Review by DStavilaNI — APPROVED** [review]

**Pull request merged**
