### PR TITLE
Update FPGA Register IO library

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR contains the latest version of the FPGA Register IO library.

### Why should this Pull Request be merged?

The current version of the FPGA Register IO library is outdated and does not contain the performance improvements for Cluster Read/Write

### What testing has been done?

Run the library unit tests with the latest version and they all passed.

### CODE REVIEW

**Review by DStavilaNI — APPROVED** [review]
I agree with the modifications

**Comment by bogdanp-ni** [comment]
Convert Bool Array to Cluster.vim - please remove dead code:

image

**Comment by bogdanp-ni** [comment]
Wherever you have a Type Specialization, please add a comment for each case stating for what datatypes is each supposed to be unbroken. Having nested malleable VIs, it's difficult for someone to understand the functionality, so comments might go a long way.

**Comment by bogdanp-ni** [comment]
Convert Cluster to Bool Array.vim.png -> small typo

image

**Comment by bogdanp-ni** [comment]
Convert Cluster BLOB to Bool Array.vi.png -> revert, no changes

**Comment by bogdanp-ni** [comment]
I suggest replacing this with a strict Equals? and compare with the expected FXP, in the exact same format:

image

It's not that I expect this to cause problems, but it's a best practice in tests to always be as strict as possible with the assertions (but without risking false positives - which is not the case here).

**Review by bogdanp-ni — APPROVED** [review]
I approve, but please address my remaining comments.

**Comment by zszilagy** [comment]
> Convert Bool Array to Cluster.vim - please remove dead code:
> 
> image

removed the unused code fragment.

**Comment by zszilagy** [comment]
> Convert Cluster to Bool Array.vim.png -> small typo
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> I suggest replacing this with a strict Equals? and compare with the expected FXP, in the exact same format:
> 
> image
> 
> It's not that I expect this to cause problems, but it's a best practice in tests to always be as strict as possible with the assertions (but without risking false positives - which is not the case here).

Fixed as requested.

**Comment by zszilagy** [comment]
> Wherever you have a Type Specialization, please add a comment for each case stating for what datatypes is each supposed to be unbroken. Having nested malleable VIs, it's difficult for someone to understand the functionality, so comments might go a long way.

Added a list with comment containing the cluster that are currently accepted by the Type Specialization structure.

**Pull request merged**
