### PR TITLE
Created System Level Tests for the FPGA Addon Status Channels

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Added 4 new system level tests which validates the functionality of the FPGA Addon\Waveform Status Channel functionality. 
The bitfiles are intended to run on a PXIe-7858 FPGA target.

### Why should this Pull Request be merged?

Currently there are no tests which are validating the functionality of the status channels.

### What testing has been done?

Run the test locally and they all passed.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
This is too weak of a passing condition for a test. Why is the value oscillating? Could a larger wait period stabilize that value? 

image

**Comment by zszilagy** [comment]
> This is too weak of a passing condition for a test. Why is the value oscillating? Could a larger wait period stabilize that value?
> 
> image

Based on a discussion with Bogdan Popa, we decided to leave this pass condition as it is, as the number of elements remaining may vary for different targets.

**Comment by DStavilaNI** [comment]
image

Isn't it DMA FIFO Write that actually producing this error ? I would expect a DMA overflow in this case, which would lead to the timeout ....

**Comment by DStavilaNI** [comment]
I would recommend implementations like this, using constants: 
image
It is extremely brittle. 

Instead, use a "While Loop" implementation, to simulate a timeout based operation:

image

**Comment by DStavilaNI** [comment]
image

This constant does seem rather magical. Can you explain how did you arrive to this value and can you be sure that it will stay unchanged during future tests ?

**Pull request merged**
