### PR TITLE
FPGA Addon - PPL migration

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Migration of the FPGA Addon to a PPL format (Build Spec updates, XML File updates, Post-Build Step update to automatically update the XML file after each build sequence, mutation code implementation)
- Builds the custom device for 2019 and 2020 32-bit and 2021 64-bit
- Removes Pharlap and Linux ARM support (together with unit and system tests updates, to account for only supported targets)

### Why should this Pull Request be merged?

- Migration of the FPGA Addon to a PPL format
- Updated the custom device according to the new target support policy as well as LabVIEW versions.

### What testing has been done?

- Manual testing has been done.
- System and unit tests are running.

### CODE REVIEW

**Review by phutanu — COMMENTED** [review]
Is there a reason for doing this?
image

When you can already do this in LabVIEW:
image

**Comment by phutanu** [comment]
> Is there a reason for doing this? image
> 
> When you can already do this in LabVIEW: image

Also, this error cluster has got some beating-up.
image

**Comment by phutanu** [comment]
How do we validate that the dependency was added successfully if this code does not report any  error when the refnum is invalid?
image

**Comment by phutanu** [comment]
Are we validating this path somewhere?
image

**Comment by phutanu** [comment]
Why do we allow dependencies for all the targets in the XML, when only `Windows` and `Linux_64` targets are supported for next release?
image

**Comment by phutanu** [comment]
Typo:
image

**Comment by DStavilaNI** [comment]
It will not be merged into main

**Pull request closed without merging**
