### PR TITLE
Refactored the 'Get Active Scalar Section.vi'

### PR DESCRIPTION
**Pull request by zszilagy**
Also a few unrelated VIs were arranged and cleaned up

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Refactored the 'Get Active Scalar Section.vi'. Also, all VIs which are used by the 'Reload Bitfile.vi' were re-arranged for better readability.

### Why should this Pull Request be merged?

Currently it's hard to track what happens inside 'Get Active Scalar Section.vi' due to the numerous cases and complex wiring.

### What testing has been done?

Built the Custom Device and went through all the test cases which were applied during for the original implementation of the 'Bitfile Reload' functionality.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Remove Invalid Scalars - please change the radix of the constant to "hex".

**Comment by bogdanp-ni** [comment]
Some of the VIs appear as changed, but without any actual changes.

**Review by bogdanp-ni — APPROVED** [review]
Please see my comments above.

The code looks much better now!

**Comment by DStavilaNI** [comment]
The implementation looks good, however I have a bunch of comments:

1. The names for these VIs are not reflecting the actual functionality:
 
image

"Build Scalar Channel.vi" does not actually build a channel. It simply repacks the data from one cluster to another. I think it should be rather along the lines of "Generate Scalar Channel Data.vi" ...or something similar. Otherwise, I think the name is misleading.

image

"Get Valid Item Ref.vi" - this is not an actual "Get" ... this is more of a search function, since this is what it does. You give it a bitfile name, and it returns a channel reference. It should be along the lines of "Find Channel Ref.vi" ... or something similar. 

2. I think that this implementation should be revised since it can be rather misleading:

image

This function checks for null reference returned by the "Get Bitfile Object ref.vi". "Get Bitfile Object ref.vi" will return a null reference only if a channel reference for a given bitfile name is not found in the input array - so the condition is known. It makes more sense to simply have "Get Bitfile Object ref.vi" return a boolean "Found" that would directly validate the returned reference, rather than checking one more time that reference outside the function to get the boolean. In this case, the "Not a ref" output actually is used to tell if a channel reference was found, and not to actually validate the reference.  Validating a reference with "Not a ref.vi" would make sense only if the source of the reference would be unknown (a VI takes in a reference, and we don't know where does that reference comes from of if it's valid)

3. The above comments apply here as well:

image

**Comment by zszilagy** [comment]
> The implementation looks good, however I have a bunch of comments:
> 
> 1. The names for these VIs are not reflecting the actual functionality:
> 
> image
> 
> "Build Scalar Channel.vi" does not actually build a channel. It simply repacks the data from one cluster to another. I think it should be rather along the lines of "Generate Scalar Channel Data.vi" ...or something similar. Otherwise, I think the name is misleading.
> 
> image
> 
> "Get Valid Item Ref.vi" - this is not an actual "Get" ... this is more of a search function, since this is what it does. You give it a bitfile name, and it returns a channel reference. It should be along the lines of "Find Channel Ref.vi" ... or something similar.
> 
> 1. I think that this implementation should be revised since it can be rather misleading:
> 
> image
> 
> This function checks for null reference returned by the "Get Bitfile Object ref.vi". "Get Bitfile Object ref.vi" will return a null reference only if a channel reference for a given bitfile name is not found in the input array - so the condition is known. It makes more sense to simply have "Get Bitfile Object ref.vi" return a boolean "Found" that would directly validate the returned reference, rather than checking one more time that reference outside the function to get the boolean. In this case, the "Not a ref" output actually is used to tell if a channel reference was found, and not to actually validate the reference. Validating a reference with "Not a ref.vi" would make sense only if the source of the reference would be unknown (a VI takes in a reference, and we don't know where does that reference comes from of if it's valid)
> 
> 1. The above comments apply here as well:
> 
> image

Changes were made and the suggested items were implemented.

**Comment by DStavilaNI** [comment]
> 
> 
> > The implementation looks good, however I have a bunch of comments:
> > 
> > 1. The names for these VIs are not reflecting the actual functionality:
> > 
> > image
> > "Build Scalar Channel.vi" does not actually build a channel. It simply repacks the data from one cluster to another. I think it should be rather along the lines of "Generate Scalar Channel Data.vi" ...or something similar. Otherwise, I think the name is misleading.
> > image
> > "Get Valid Item Ref.vi" - this is not an actual "Get" ... this is more of a search function, since this is what it does. You give it a bitfile name, and it returns a channel reference. It should be along the lines of "Find Channel Ref.vi" ... or something similar.
> > 
> > 1. I think that this implementation should be revised since it can be rather misleading:
> > 
> > image
> > This function checks for null reference returned by the "Get Bitfile Object ref.vi". "Get Bitfile Object ref.vi" will return a null reference only if a channel reference for a given bitfile name is not found in the input array - so the condition is known. It makes more sense to simply have "Get Bitfile Object ref.vi" return a boolean "Found" that would directly validate the returned reference, rather than checking one more time that reference outside the function to get the boolean. In this case, the "Not a ref" output actually is used to tell if a channel reference was found, and not to actually validate the reference. Validating a reference with "Not a ref.vi" would make sense only if the source of the reference would be unknown (a VI takes in a reference, and we don't know where does that reference comes from of if it's valid)
> > 
> > 1. The above comments apply here as well:
> > 
> > image
> 
> Changes were made and the suggested items were implemented.

I believe that the process can further be improved. For example:

1. 
image

The "boolean" output of this VI is still called "Not a ref" - I think this should not longer be the case, since in fact it returns whether or not a reference was found. Moreover, it is misleading, considering how this output is used:

image

so, if ("Not a ref" == True) than do stuff to that reference ... I think this should be addressed, since it is incorrect/reversed logic.

2. I think that this could be simplified:

  image

This VI is essentially just an  Error Case Structure around another VI, which makes one of the two redundant. I would recommend keeping "Find Valid Item Ref.vi".

3. It seems that the project is missing the "FPGA Addon Reload Bitfile" unit tests ... I think you should sync-up with the main branch of this repo.

**Comment by DStavilaNI** [comment]
I would recommend that if you changed the name of the VIs, than please update the names of the controls to reflect the functionality:

image

... I think it should be for example "scalar channel data out" 

similarly here:

image

**Pull request merged**
