### PR TITLE
Added the libraries along with the template VIs to the FPGA Addon Project (FXP Support)

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?
This pull requests contains the Library and folder structure in which the new Read and Write methods for Scalar and Speciality IO registers will be organized. Template VIs along with the Polymorphic VIs were also added.

### Why should this Pull Request be merged?

This PR contains the infrastructure which helps to keep Read/Write methods for Scalar registers organized.

### What testing has been done?

N/A

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Do you plan on adding text to the icons in another PR? Because now would also be a good time for that.

**Comment by bogdanp-ni** [comment]
Is there a reason why the Speciality IO VIs don't use typedefs for their specific controls/indicators?

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my previous comments.

**Comment by zszilagy** [comment]
Moving this to the DEV branch. Closing the PR>

**Pull request closed without merging**
