### PR TITLE
SysDef Opening - reload the FPGA bitfile 

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- When opening a SysDef containing an FPGA  Addon CD, the bitfile (if available) is reloaded. This enables the bitfile to be reparsed and all of it's contained registers displayed properly in the SE.

### Why should this Pull Request be merged?

- If the target bitfile was modified (added or removed registers), or if the new version of the FPGA Addon CD is used on a System Definition configured with an earlier version of the same CD, the implementation enables all of the registers contained in the bitfile to be displayed properly in the System Explorer.

### What testing has been done?

- Local/manual testing has been done on the dev machine

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
The issue described in the bug may arise _only_ when the FPGA Addon is mutated. Therefore, are there any side effects to doing a Reload of the bitfile when the FPGA Addon is not mutated? I can't think of any, but wanted to hear your confirmation.

**Comment by bogdanp-ni** [comment]
We discussed about the case where a sysdef with FPGA Addon is opened on another machine and the bitfile is not found anymore. I remember you were saying that that error  is reported by VS and not by the CD itself. Is that error thrown before or after ActionVIonLoad runs? Because if ActionVIonLoad runs first, it will error out, because of the same missing bitfile issue, and I'd like to make sure the error can be properly understood by the user (we might need to format the error). If, in fact, VS will still throw the error first, then we don't need to do anything.

**Review by bogdanp-ni — APPROVED** [review]
I agree with the change. I left two comments that may or may not involve changes, please address them before submitting.

**Comment by DStavilaNI** [comment]
> 
> 
> The issue described in the bug may arise _only_ when the FPGA Addon is mutated. Therefore, are there any side effects to doing a Reload of the bitfile when the FPGA Addon is not mutated? I can't think of any, but wanted to hear your confirmation.

Hello :) ... I think that this issue is not specific only to a situation involving mutation. The CD version could stay the same, however the user could simply go and modify something in the bitfile (add/remove controls or indicators) - the effect would be the same. That being said, the reload code executes after the mutation code (which might execute or not), and only if there were no errors before.  To put it in different words - the execution of the reload code is not impacted by whether the execution of the mutation code happened or not, as long as there were no errors.

**Comment by bogdanp-ni** [comment]
> > The issue described in the bug may arise _only_ when the FPGA Addon is mutated. Therefore, are there any side effects to doing a Reload of the bitfile when the FPGA Addon is not mutated? I can't think of any, but wanted to hear your confirmation.
> 
> Hello :) ... I think that this issue is not specific only to a situation involving mutation. The CD version could stay the same, however the user could simply go and modify something in the bitfile (add/remove controls or indicators) - the effect would be the same. That being said, the reload code executes after the mutation code (which might execute or not), and only if there were no errors before. To put it in different words - the execution of the reload code is not impacted by whether the execution of the mutation code happened or not, as long as there were no errors.

I agree with your point, I didn't think of the "bitfile was changed while VS was closed" scenario!

**Comment by DStavilaNI** [comment]
> 
> 
> We discussed about the case where a sysdef with FPGA Addon is opened on another machine and the bitfile is not found anymore. I remember you were saying that that error is reported by VS and not by the CD itself. Is that error thrown before or after ActionVIonLoad runs? Because if ActionVIonLoad runs first, it will error out, because of the same missing bitfile issue, and I'd like to make sure the error can be properly understood by the user (we might need to format the error). If, in fact, VS will still throw the error first, then we don't need to do anything.

To answer this question - before running the reload code, we are checking if the bitfile at the specified path exists. If it does not exist then this operation is simply ignored (silently). The reason why we are doing it this way is because, as you mentioned, the SE already does a similar check for dependend files and notifies the user if something is missing. I believe that this is happening before the "ActionVIOnLoad.vi", therefore no extra error handling is needed (in my opinion).

**Comment by bogdanp-ni** [comment]
> > We discussed about the case where a sysdef with FPGA Addon is opened on another machine and the bitfile is not found anymore. I remember you were saying that that error is reported by VS and not by the CD itself. Is that error thrown before or after ActionVIonLoad runs? Because if ActionVIonLoad runs first, it will error out, because of the same missing bitfile issue, and I'd like to make sure the error can be properly understood by the user (we might need to format the error). If, in fact, VS will still throw the error first, then we don't need to do anything.
> 
> To answer this question - before running the reload code, we are checking if the bitfile at the specified path exists. If it does not exist then this operation is simply ignored (silently). The reason why we are doing it this way is because, as you mentioned, the SE already does a similar check for dependend files and notifies the user if something is missing. I believe that this is happening before the "ActionVIOnLoad.vi", therefore no extra error handling is needed (in my opinion).

To explain - I'm ok with the current error reporting:
image

Please do a simple manual check with the new implementation - delete the bitfile before loading a sysdef that was referencing that bitfile. It should still have the same error shown as above (no other error, no duplicate errors for the same missing bitfile).

**Pull request merged**
