### PR TITLE
Review Examples and QSG

### PR DESCRIPTION
**Pull request by phutanu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Updates the Examples to a more readable and useful format.
- Removes old and outdated content.

### Why should this Pull Request be merged?

- To help users be more successful using the full functionality of FPGA Addon.
- To help users have access to up-to-date documentation.

### What testing has been done?

- Scripting API Examples run on the development machine.

### CODE REVIEW

**Comment by DStavilaNI** [comment]
Regarding the changes themselves, I would have a couple of comments: 

1.  Scalar Channels Example

image

I think that the note should be more clearly differentiated from the rest of the enumerated list - consider using some separator lines.
 
2. I believe that in some places the font sizes are not ideal from a visual point of view:
 
image

I think that the paragraph text size looks as big or even bigger than the paragraph title and ends up capturing too much focus from the reader. 

Other files affected:
- Scalar Channels Example
- Speciality IO Example

 3. Typo:
 
image

Should be "Imports" if I understood correctly the flow of the rest of the list.

**Comment by DStavilaNI** [comment]
Some questions from my side: 

1. Why were the Scripting API Examples renamed ? For example, what is the benefit of having "Create an FPGA Addon and import scalars.vi" instead of "Example 3 - Create FPGA Addon and Import Scalars.vi"

2. Why were the modifications to the "DMA Channels Interleaved Example", "Scalar Channels Example" and "Speciality IO Example" Readme.md files made ? As I checked in the tech debt item, this was not requested - therefore I would like to understand the purpose/benefit of the changes.

**Comment by phutanu** [comment]
> 1. Why were the Scripting API Examples renamed ? For example, what is the benefit of having "Create an FPGA Addon and import scalars.vi" instead of "Example 3 - Create FPGA Addon and Import Scalars.vi"

As the specific request from our PO was to remove "Example x" from the naming and leave just what the example does.

> 2. Why were the modifications to the "DMA Channels Interleaved Example", "Scalar Channels Example" and "Speciality IO Example" Readme.md files made ? As I checked in the tech debt item, this was not requested - therefore I would like to understand the purpose/benefit of the changes.

This change was made from the goodness of my heart, just because they contained old instructions and were not consistent with the feedback we got from our tech writer on the examples from the Instrument Addon.

**Review by bogdanp-ni — APPROVED** [review]
I approve the change, as long as the typos and small kinks are ironed out. I agree with the new names for the examples VIs.

**Review by DStavilaNI — CHANGES_REQUESTED** [review]
I approve once the requested changes are submitted

**Pull request merged**
