### PR TITLE
FPGA Addon Scripting API - Create FPGA Addon & Find FPGA Addon Unit Tests

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Created Unit Tests for the "Create FPGA  Addon.vi"
- Created Unit Test for Find FPGA  Addon.vi
- Created Unit Test for Find FPGA  Addons.vi
- BugFix within the "Find FPGA  Addon.vi"
- Creates the File/Folder structure for the Scripting API Unit Tests

### Why should this Pull Request be merged?

- Same as the above

### What testing has been done?

- Local testing has been done on the dev machine.
- Manual testing has been done

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Please remove testExample.vit

**Comment by bogdanp-ni** [comment]
Please remove testExample 1.vi (although I only see it in the diffbot's comment and not in the list of changed files).

**Comment by bogdanp-ni** [comment]
Please rename the following files, according to our team's conventions:
test_Create FPGA Addon--Error.vi -> test_Create FPGA Addon_Error.vi
test_Create FPGA Addon--Group Scalars.vi -> test_Create FPGA Addon_Group Scalars.vi

**Comment by bogdanp-ni** [comment]
Why is there a need for this new VI that does validation? FPGA Addon Test Class.lvclass--isValid FPGA Addon.vi

Since it is identical to the one in the Scripting API library, I would like for the tests to use that one as well, instead of duplicating the functionality.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my comments above.

**Comment by bogdanp-ni** [comment]
One more thing: please rename the test class from "Scripting API Unit Tests.lvclass" to "FPGA Addon Scripting API Unit Tests.lvclass". The class name is how we identify the tests on the autotest runner and our convention is to always start with the CD name, to aid searching.

**Comment by DStavilaNI** [comment]
> 
> 
> Why is there a need for this new VI that does validation? FPGA Addon Test Class.lvclass--isValid FPGA Addon.vi
> 
> Since it is identical to the one in the Scripting API library, I would like for the tests to use that one as well, instead of duplicating the functionality.

In the Scripting Library, that subVI is set as private - I did this on purpose. It is not supposed to be used outside the library. Therefore it cannot be used in the test classes. I would like it to stay this way.

**Comment by bogdanp-ni** [comment]
> > Why is there a need for this new VI that does validation? FPGA Addon Test Class.lvclass--isValid FPGA Addon.vi
> > Since it is identical to the one in the Scripting API library, I would like for the tests to use that one as well, instead of duplicating the functionality.
> 
> In the Scripting Library, that subVI is set as private - I did this on purpose. It is not supposed to be used outside the library. Therefore it cannot be used in the test classes. I would like it to stay this way.

Personally, I believe that the need for that functionality outside of the library is the precise indication that the subVI should not be private, in this case. But since I see little chance that these two implementations could diverge, I'm ok with keeping the duplication code in the test class.

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
