### PR TITLE
Add unit and system level tests to validate the "Reload Bitfile" feature

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds further unit tests which validates the functionality of the "Reload Bitfile" functionality.
These tests focus on validating the Scalar Channel and DMA Channel behavior when the bitfile reload functionality gets triggered. Both unit tests and system level tests were added to the project.
Also, a fix for the Static Scalar Channel handling was implemented which provides solution for how static scalar channels are handled by the bitfile reload functionality.
The Custom device XML was updated in order to add a "Delete Channel" option for the static scalar channels.

### Why should this Pull Request be merged?

Not all corner cases are covered with the current unit tests.

### What testing has been done?

Run the tests locally and they all passed.

### CODE REVIEW

**Comment by DStavilaNI** [comment]
The idea of the the test is good, however the test itself does not show or prove that there was a change in the datatype. In both deployments, the channel values are read as doubles, therefore we have to "trust" the author and the description to be accurate and that a datatype change actually occurred - I believe that this is not necessarily defying the purpose of the test, but makes the purpose of the test less apparent and harder to debug (you need to check the bitfiles to see what exactly is happening.) 

My opinion is that the Scripting API could and should be used to "prove" the data-types before the deployments, to validate the change for a control of the same name. Additionally, extra data-types should be used - like FXP for example to cover a wider range.

**Comment by bogdanp-ni** [comment]
Please create non-generic icons for these VIs. Text-only will do just fine.

**Comment by bogdanp-ni** [comment]
Do we have tests with Speciality IO? Would it make sense to add such tests? I'd like us to discuss it.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my comments above.

**Comment by zszilagy** [comment]
> Please create non-generic icons for these VIs. Text-only will do just fine.

Updated the missing icons.

**Comment by zszilagy** [comment]
> Do we have tests with Speciality IO? Would it make sense to add such tests? I'd like us to discuss it.

There will be a fix submitted in the near future for the speciality IO functionality. The tests will be included in that pull request.

**Pull request merged**
