### PR TITLE
DMA Channels Interleaved Testing

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implemented testing for the DMA Channels Interleaved feature
- Refactoring of the DMA Channels Basic Testing ( Added - "Read Waveform Channel(Multiple).vi" )

### Why should this Pull Request be merged?

It solves the User Story which treats the testing of the DMA Channels Interleaved feature 

### What testing has been done?

Tests have been done on the development machine.
Consecutive tests are failing due to the VeriStand bug described [here](https://ni.visualstudio.com/DevCentral/_boards/board/t/ASW%20G%20Ecosystem/Work%20Items/?workitem=1059694).

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Please rename: "Get Waveform Path from Spec" OR "Get Waveform Path from Waveform Spec"

image

**Comment by bogdanp-ni** [comment]
I see duplicated code between DMA Channels Basic and Interleaved classes. Why did you decide against using a common parent class?

**Comment by bogdanp-ni** [comment]
Please update the PR Description, since now it only covers Interleaved tests, and I noticed both Basic and Max Nr of Scalar Channels have been touched.

**Comment by bogdanp-ni** [comment]
Why is there no assertion in test_Basic Waveform Read?

**Comment by DStavilaNI** [comment]
> 
> 
> Please rename: "Get Waveform Path from Spec" OR "Get Waveform Path from Waveform Spec". It looks misleading that "waveform" is both written in full and then abbreviated, in the same VI name.
> 
> image

Honestly, it was from the lack of inspiration. The full name would have been "Get Waveform Path from WaveformStreamSpecification.vi" ... I hate long paths/names :( and did not find a better one.  I will look into renaming it, or if you have other ideas, they are more then welcome.

**Comment by DStavilaNI** [comment]
> 
> 
> I see duplicated code between DMA Channels Basic and Interleaved classes. Why did you decide against using a common parent class?

I want to avoid exceedingly long hierarchy paths. This can lead to fragile code structures. With the current test cases, we are already at 4 levels of inheritance.... I did not want to create one more. The sensible thing to do, would be to move some methods to the FPGA Addon Test Class, which is the closest ancestor, however this would imply refactoring and will also affect other child classes. I would consider this only if there will be other situations where these functions will be required ... but it seems that we implemented most of our development user stories.

**Comment by DStavilaNI** [comment]
> 
> 
> Please update the PR Description, since now it only covers Interleaved tests, and I noticed both Basic and Max Nr of Scalar Channels have been touched.

I did refactor the Basic DMA Testing ... but I did not touch the Max Nr of Scalar Channels test cases. At least not on purpose :) - the functionality is unchanged.  Anyways, I will document it.

**Comment by DStavilaNI** [comment]
> 
> 
> Why is there no assertion in test_Basic Waveform Read?

There was no need for an assertion since the idea of the test case was to attempt reading a waveform. The test would fail if there is an error during the read operation, but would not check the data. This would be done later ... but I think I could document and maybe modify this test case, to make it more robust.

**Comment by bogdanp-ni** [comment]
> > Please rename: "Get Waveform Path from Spec" OR "Get Waveform Path from Waveform Spec". It looks misleading that "waveform" is both written in full and then abbreviated, in the same VI name.
> > image
> 
> Honestly, it was from the lack of inspiration. The full name would have been "Get Waveform Path from WaveformStreamSpecification.vi" ... I hate long paths/names :( and did not find a better one. I will look into renaming it, or if you have other ideas, they are more then welcome.
> 
> Edit: Modified it

I still see "Get Waveform Path from WvfmSpec.vi". Let's go with "Get Waveform Path from Spec", since we don't seem to have a better option.

**Comment by bogdanp-ni** [comment]
> > I see duplicated code between DMA Channels Basic and Interleaved classes. Why did you decide against using a common parent class?
> 
> I want to avoid exceedingly long hierarchy paths. This can lead to fragile code structures. With the current test cases, we are already at 4 levels of inheritance.... I did not want to create one more. The sensible thing to do, would be to move some methods to the FPGA Addon Test Class, which is the closest ancestor, however this would imply refactoring and will also affect other child classes. I would consider this only if there will be other situations where these functions will be required ... but it seems that we implemented most of our development user stories.

I see your point, having exceedingly large inheritance trees is a bad practice. But so is repeated code, especially in the same class/library/component. I'm ok with keeping this code as-is, but for future cases we must either add a new parent, or extract another "helper" class (not in the same inheritance hierarchy, but that we can use for composition).

**Comment by DStavilaNI** [comment]
> 
> 
> > > I see duplicated code between DMA Channels Basic and Interleaved classes. Why did you decide against using a common parent class?
> > 
> > 
> > I want to avoid exceedingly long hierarchy paths. This can lead to fragile code structures. With the current test cases, we are already at 4 levels of inheritance.... I did not want to create one more. The sensible thing to do, would be to move some methods to the FPGA Addon Test Class, which is the closest ancestor, however this would imply refactoring and will also affect other child classes. I would consider this only if there will be other situations where these functions will be required ... but it seems that we implemented most of our development user stories.
> 
> I see your point, having exceedingly large inheritance trees is a bad practice. But so is repeated code, especially in the same class/library/component. I'm ok with keeping this code as-is, but for future cases we must either add a new parent, or extract another "helper" class (not in the same inheritance hierarchy, but that we can use for composition).

I agree.

**Comment by DStavilaNI** [comment]
> 
> 
> > > Please rename: "Get Waveform Path from Spec" OR "Get Waveform Path from Waveform Spec". It looks misleading that "waveform" is both written in full and then abbreviated, in the same VI name.
> > > image
> > 
> > 
> > Honestly, it was from the lack of inspiration. The full name would have been "Get Waveform Path from WaveformStreamSpecification.vi" ... I hate long paths/names :( and did not find a better one. I will look into renaming it, or if you have other ideas, they are more then welcome.
> > Edit: Modified it
> 
> I still see "Get Waveform Path from WvfmSpec.vi". Let's go with "Get Waveform Path from Spec", since we don't seem to have a better option.

Renamed it with "Get Wfm Path from WfmStreamSpec.vi", also it's in the current commit ;)

image

**Comment by bogdanp-ni** [comment]
> > > > Please rename: "Get Waveform Path from Spec" OR "Get Waveform Path from Waveform Spec". It looks misleading that "waveform" is both written in full and then abbreviated, in the same VI name.
> > > > image
> > > 
> > > 
> > > Honestly, it was from the lack of inspiration. The full name would have been "Get Waveform Path from WaveformStreamSpecification.vi" ... I hate long paths/names :( and did not find a better one. I will look into renaming it, or if you have other ideas, they are more then welcome.
> > > Edit: Modified it
> > 
> > 
> > I still see "Get Waveform Path from WvfmSpec.vi". Let's go with "Get Waveform Path from Spec", since we don't seem to have a better option.
> 
> Renamed it with "Get Wfm Path from WfmStreamSpec.vi", also it's in the current commit ;)
> 
> image

By looking at the Files changed tab, I see this:
image

And no sign of the new, renamed file.

**Comment by bogdanp-ni** [comment]
_Now_ I see it, there were two files :)

Nevertheless, since both files are doing (more or less) the same thing, please make sure they are both named the same.

**Comment by DStavilaNI** [comment]
> 
> 
> _Now_ I see it, there were two files :)
> 
> Nevertheless, since both files are doing (more or less) the same thing, please make sure they are both named the same.

Done ;) ... I actually missed that one. Thx.

**Pull request merged**
