### PR TITLE
FPGA Addon Scripting API - Unit Tests

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

-> Implemented unit tests for:
  - Get Bitfile Scalars.vi
  - Set FPGA Bitfile.vi
  - Get FPGA Bitfile.vi
  - Set RIO Resource.vi
  - Get RIO Resource.vi

-> Fixed icons for other unit tests to maintain consistency.
-> BugFix within the "Set FPGA Bitfile.vi" (path was not saved).

### Why should this Pull Request be merged?

- See above

### What testing has been done?

- Local/manual testing has been done

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
test_Get Bitfile Scalars.vi is missing from FPGA Addon Scripting API Unit Tests.lvclass, please add it:

image

**Comment by bogdanp-ni** [comment]
Same for Compare Scalar Clusters.vi

**Comment by bogdanp-ni** [comment]
Compare Scalar Clusters.vi might return an incorrect result if the two arrays to be compared are of different sizes, because the Equal will compare only to the shortest array's length (and ignore the remaining elements of the longer array). Actually, instead of this entire VI, just use a  simple Equals? with the Comparison Mode set to "Compare Aggregates" (which will also see if lengths match). Here's an example of the incorrect behavior (and, by contrast, using an Equals with Compare Aggregates that returns false, as expected):
image
image

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my comments above.

**Comment by DStavilaNI** [comment]
> 
> 
> Compare Scalar Clusters.vi might return an incorrect result if the two arrays to be compared are of different sizes, because the Equal will compare only to the shortest array's length (and ignore the remaining elements of the longer array). Actually, instead of this entire VI, just use a simple Equals? with the Comparison Mode set to "Compare Aggregates" (which will also see if lengths match). Here's an example of the incorrect behavior (and, by contrast, using an Equals with Compare Aggregates that returns false, as expected):
> image
> image

Yup - good catch here ... did not think about different sizes

**Comment by bogdanp-ni** [comment]
In test_Set FPGA Bitfile_Error.vi, there's this node overlapping the wire label:

image

**Review by bogdanp-ni — APPROVED** [review]
The change looks good, please fix the small visual issue (my last comment).

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
