### PR TITLE
Scripting API - Implementation

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Offers a first implementation of the Scripting API for the FPGA Addon, in accordance to the current proposal of the HLD draft.
- Provides build specs for packaging the Scripting API into a distributable packed project library.
- The FPGA Addon Scripting API includes currently in the distribution multiple palette files that allow ease of use with the LabVIEW development environment.

### Why should this Pull Request be merged?

- Offers a first implementation of the FPGA Addon Scripting API

### What testing has been done?

- Local manual testing has been done for both the FPGA Addon Scripting API: Source version and the distributable library

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Minor icon change - it should say "LV" instead of "VS" (or something similar):

image

**Comment by bogdanp-ni** [comment]
In Create FPGA Addon, there's a hanging error wire. Please merge it into the other error wire:
image

**Comment by bogdanp-ni** [comment]
Find FPGA Addon Custom Devices.vi -> please see my comment in the HLD PR about renaming this to "Find All FPGA Addons".

**Comment by bogdanp-ni** [comment]
In Find FPGA Addon, there should be a GUID filtering (like in Find All FPGA Addons) step before searching by name. Right now, this node will return any type of CD, if the name matches.

image

**Comment by bogdanp-ni** [comment]
Delete FPGA Addon - interface does not match what is in the HLD. Please update the HLD and use "deleted?" (all-lowercase) for the new indicator:
image

**Comment by bogdanp-ni** [comment]
The naming on "Export" and "Import" VIs doesn't match the HLD. Please go with "Export/Import FPGA Addon Configuration", to have the same format like for "Create FPGA Addon" and "Delete FPGA Addon". And use "Import Configuration/Config" and "Export Configuration/Config" for the short palette names, to keep the name fully visible.

image

**Comment by bogdanp-ni** [comment]
In Import Configuration, just for my curiosity - why does only "Group" need to be specifically set to False? Aren't all 'properties' expected to be overwritten, since "Overwrite Existing?" is set to True? 
image

**Comment by bogdanp-ni** [comment]
Clear Scalar Channels - please add refnum validation.

**Comment by bogdanp-ni** [comment]
Set FPGA Bitfile - please rename control from "fpga bitfile path" to "FPGA bitfile path", like in the HLD.

image

**Comment by bogdanp-ni** [comment]
Like in the HLD, please rename these to "Import Scalars - All.vi" and "Import Scalars - By Label.vi"

image

**Comment by bogdanp-ni** [comment]
There is a duplicated error code (5002) in Create Addon and Add Scalar to Group:

image

image

**Comment by bogdanp-ni** [comment]
Please add proper icons to all newly-added typedefs.

**Comment by bogdanp-ni** [comment]
Please add documentation for all public VIs.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my comments above.

Except the issues I noticed, the actual implementation looks good!

**Comment by DStavilaNI** [comment]
> 
> 
> Minor icon change - it should say "LV" instead of "VS" (or something similar):
> 
> image

Fixed

**Comment by DStavilaNI** [comment]
> 
> 
> In Create FPGA Addon, there's a hanging error wire. Please merge it into the other error wire:
> image

Fixed

**Comment by DStavilaNI** [comment]
> 
> 
> Delete FPGA Addon - interface does not match what is in the HLD. Please update the HLD and use "deleted?" (all-lowercase) for the new indicator:
> image

Fixed

**Comment by DStavilaNI** [comment]
> 
> 
> The naming on "Export" and "Import" VIs doesn't match the HLD. Please go with "Export/Import FPGA Addon Configuration", to have the same format like for "Create FPGA Addon" and "Delete FPGA Addon". And use "Import Configuration/Config" and "Export Configuration/Config" for the short palette names, to keep the name fully visible.
> 
> image

Fixed

**Comment by DStavilaNI** [comment]
> 
> 
> Clear Scalar Channels - please add refnum validation.

Applied

**Comment by DStavilaNI** [comment]
> 
> 
> Clear Scalar Channels - please add refnum validation.

Applied

**Comment by DStavilaNI** [comment]
> 
> 
> Set FPGA Bitfile - please rename control from "fpga bitfile path" to "FPGA bitfile path", like in the HLD.
> 
> image

Applied

**Comment by DStavilaNI** [comment]
> 
> 
> Like in the HLD, please rename these to "Import Scalars - All.vi" and "Import Scalars - By Label.vi"
> 
> image

Applied

**Comment by DStavilaNI** [comment]
> 
> 
> There is a duplicated error code (5002) in Create Addon and Add Scalar to Group:
> 
> image
> 
> image

Fixed

**Comment by bogdanp-ni** [comment]
Find FPGA Addon Custom Devices.vi -> please rename to "Find FPGA Addons.vi", to match HLD.

**Review by bogdanp-ni — APPROVED** [review]
The changes look good. I have one renaming request and afterwards this is ready to go.

**Pull request merged**
