### PR TITLE
Fixing the cluster read/write issue in the FPGA Register IO library.

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR contains the latest version of the FPGA Register IO library containing improvements regarding packing and unpacking clusters to/from Array U32/ Array U8.

### Why should this Pull Request be merged?

The current implementation has issues with number of bytes which are not multiples of 4 when it comes to read/write operations. This PR contains a fix for this issue.

### What testing has been done?

Built the CD and tested in NI VeriStand. The issues known regarding the Cluster Read/Write appears to be fixed in the latest version.

### CODE REVIEW

**Review by DStavilaNI — APPROVED** [review]
I approve the changes

**Comment by bogdanp-ni** [comment]
Convert Bool Array to Cluster -> you removed that dead code in a previous PR, I'm guessing it's back by mistake. Please delete it.

image

**Comment by bogdanp-ni** [comment]
Please add more details in the PR description about the issues that were fixed.

**Comment by bogdanp-ni** [comment]
Also, the name of the PR should reflect what was fixed, not that we're integrating from an unknown source.

**Comment by bogdanp-ni** [comment]
Was this issue uncovered by an existing test? If that's not the case, then please add a new test.

**Comment by zszilagy** [comment]
> Convert Bool Array to Cluster -> you removed that dead code in a previous PR, I'm guessing it's back by mistake. Please delete it.
> 
> image

Removed.

**Comment by zszilagy** [comment]
> Please add more details in the PR description about the issues that were fixed.

Details added.

**Comment by zszilagy** [comment]
> Also, the name of the PR should reflect what was fixed, not that we're integrating from an unknown source.

PR Title changed.

**Comment by zszilagy** [comment]
> Was this issue uncovered by an existing test? If that's not the case, then please add a new test.

The issues were discovered during manual testing. Tests will follow when covering Speciality IO testing in a separate PR.

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
