### PR TITLE
Implement register write unit tests

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds Register Write unit tests. 
Updates the FPGA Register IO library to the latest version.

### Why should this Pull Request be merged?

FPGA Register IO library is outdated.
Currently there are no unit tests for the Write operations of the FPGA Register IO library.

### What testing has been done?

Run all the unit tests locally and they all passed.

### CODE REVIEW

**Comment by DStavilaNI** [comment]
How do we validate that the "Write" operation works ? 

image

We are checking that the "Read" operation behaves as expected, based on the bitfile, by checking that the values are incrementing and monotones. However, how does the test validated that the "Write" value is actually written ? I think that the test should be updated to check for the written value.

Additionally, I am not sure it makes sense to keep writing continuously the same value. If the idea of the test is to have only one distinct value written, then we might as well place the "Write" function outside and before the while loop. (As a different idea, if we want to keep the "Write" operation inside the loop, then it would make sense to change the written value periodically.)

**Comment by DStavilaNI** [comment]
For the Bool test, similarly, if the written value does not change, it would make more sense to invoke the "Write" operation only once outside and before the "While" loop.

image

**Comment by zszilagy** [comment]
> How do we validate that the "Write" operation works ? This comment applies to all of the numeric tests.
> 
> image
> 
> We are checking that the "Read" operation behaves as expected, based on the bitfile, by checking that the values are incrementing and monotones. However, how does the test validated that the "Write" value is actually written ? I think that the test should be updated to check for the written value.
> 
> Additionally, I am not sure it makes sense to keep writing continuously the same value. If the idea of the test is to have only one distinct value written, then we might as well place the "Write" function outside and before the while loop. (As a different idea, if we want to keep the "Write" operation inside the loop, then it would make sense to change the written value periodically.)

The Write operation was moved outside the For loop for every Write VI.

**Comment by zszilagy** [comment]
> For the Bool test, similarly, if the written value does not change, it would make more sense to invoke the "Write" operation only once outside and before the "While" loop.
> 
> image

Fixed as suggested.

**Comment by DStavilaNI** [comment]
This is applicable for all of the Numeric tests - I do not think that this is a correct approach. 

image

What if the value read from the FPGA of always 0 ?

**Comment by DStavilaNI** [comment]
If we only need the second element from the resulting cluster array, then why do we need to read for 6s ?

image

**Comment by zszilagy** [comment]
> This is applicable for all of the Numeric tests - I do not think that this is a correct approach.
> 
> image
> 
> What if the value read from the FPGA is always 0 or a bigger integer (ex: 1, 2, 3, 4, 5)?

More accurate validation method was implemented for every test.

**Comment by bogdanp-ni** [comment]
FPGA Register IO Tests.lvclass--Get Conifg File Path.vi.png -> typo, Config

**Comment by bogdanp-ni** [comment]
FPGA Register IO Tests.lvclass--test_Write Bool Register Value.vi.png
Looking at the following snip:
image

If a single iteration will execute the False case, then this Equals will again return True, thus making it too weak of a test condition. 

I suggest a simplification of the test:
- Write the boolean
- wait for a sufficient amount of time (2-3 seconds, for the FPGA part to be done), but this can also be done with a very simple handshaking mechanism
- Read the boolean (once) and compare

**Comment by bogdanp-ni** [comment]
I believe my above comment applies to other tests, as well.

**Comment by bogdanp-ni** [comment]
Were there any major changes to the library? I did not see any, but if there are, maybe it's best if we extract those changes into a separate PR.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See comments above.

**Comment by DStavilaNI** [comment]
> 
> 
> FPGA Register IO Tests.lvclass--test_Write Bool Register Value.vi.png
> Looking at the following snip:
> image
> 
> If a single iteration will execute the False case, then this Equals will again return True, thus making it too weak of a test condition.
> 
> I suggest a simplification of the test:
> 
>     * Write the boolean
> 
>     * wait for a sufficient amount of time (2-3 seconds, for the FPGA part to be done), but this can also be done with a very simple handshaking mechanism
> 
>     * Read the boolean (once) and compare

I was checking this test as well, together with Zoli, and it's logic - in short, the idea is that based on how the test bitfile works and the logic in the "read" loop, the output array will have 1 element only if we read a "True" value from the boolean control. If we read a "False" value, the output array will be empty. The biftfile is configured to have 1 iteration per second. So, in other words, the logic of the test is correct, in my opinion. However, I think that the test could be simplified, while achieving the same intent.

**Comment by zszilagy** [comment]
> If we only need the second element from the resulting cluster array, then why do we need to read for 6s ? Probably a good idea would be to somehow include the other values in the array in the check as well.
> 
> image

Implemented as suggested.

**Comment by zszilagy** [comment]
> Were there any major changes to the library (besides reentrancy changes, renames, etc.)? I did not see any, but if there are, maybe it's best if we extract those changes into a separate PR.

Apart from the performance optimization (reentrancy etc.), the only change made in since the last update was adding the "Write Boolean.vi" instance to the "Write Data Register.vi" polymorphic VI. (It was missed in the previous implementation)

**Comment by zszilagy** [comment]
> FPGA Register IO Tests.lvclass--Get Conifg File Path.vi.png -> typo, Config

The file name appears to be correct on my end. Might be a diffbot issue, Please see the screenshots attached:

image

image

**Comment by zszilagy** [comment]
> > FPGA Register IO Tests.lvclass--test_Write Bool Register Value.vi.png
> > Looking at the following snip:
> > image
> > If a single iteration will execute the False case, then this Equals will again return True, thus making it too weak of a test condition.
> > I suggest a simplification of the test:
> > ```
> > * Write the boolean
> > 
> > * wait for a sufficient amount of time (2-3 seconds, for the FPGA part to be done), but this can also be done with a very simple handshaking mechanism
> > 
> > * Read the boolean (once) and compare
> > ```
> 
> I was checking this test as well, together with Zoli, and it's logic - in short, the idea is that based on how the test bitfile works and the logic in the "read" loop, the output array will have 1 element only if we read a "True" value from the boolean control. If we read a "False" value, the output array will be empty. The biftfile is configured to have 1 iteration per second. So, in other words, the logic of the test is correct, in my opinion. However, I think that the test could be simplified, to make it easier to understand, while keeping the same intended behavior.

Changed the test so it's easier to understand what is happening.

**Review by bogdanp-ni — APPROVED** [review]
This PR is good to go - we agreed on how to move forward with the tests.

**Pull request merged**
